In [1]:
from argparse import Namespace

In [2]:
import pandas as pd

In [3]:
import torch

In [ ]:
from transformer_lens.model_bridge import TransformerBridge

In [5]:
#from eap.graph import Graph
#from eap import graph
from eap.utils import tokenize_plus

In [6]:
from ablation_utils.utils import make_hooks

In [7]:
from gc import collect
from torch.cuda import empty_cache

In [8]:
import os
os.environ["PYTORCH_CUDA_ALLOC_CONF"]="expandable_segments:True"

In [9]:
torch.set_grad_enabled(False)

torch.autograd.grad_mode.set_grad_enabled(mode=False)

In [10]:
DEVICE='cuda:7'

In [6]:
# import importlib
# importlib.reload(graph)

In [ ]:
# collect()
# empty_cache()

In [ ]:
if "WORK" not in os.environ:
    os.environ["WORK"] = '..'
DATA_DIR = os.environ["WORK"] + '/RW_functionalities_results'

In [ ]:
subnodes_df = pd.read_csv(DATA_DIR + '/subnodes.csv')

## Inspecting df

In [11]:
subnodes_df.head(40)

    Unnamed: 0      name  layer node_name  subnode_index         score
0            0     input      0     input            NaN  0.000000e+00
1            1     a0.h0      0     a0.h0            NaN  0.000000e+00
2            2     a0.h1      0     a0.h1            NaN  0.000000e+00
3            3     a0.h2      0     a0.h2            NaN  0.000000e+00
4            4     a0.h3      0     a0.h3            NaN  0.000000e+00
5            5     a0.h4      0     a0.h4            NaN  0.000000e+00
6            6     a0.h5      0     a0.h5            NaN  0.000000e+00
7            7     a0.h6      0     a0.h6            NaN  0.000000e+00
8            8     a0.h7      0     a0.h7            NaN  0.000000e+00
9            9     a0.h8      0     a0.h8            NaN  0.000000e+00
10          10     a0.h9      0     a0.h9            NaN  0.000000e+00
11          11    a0.h10      0    a0.h10            NaN  0.000000e+00
12          12    a0.h11      0    a0.h11            NaN  0.000000e+00
13          13    a0.h12      0    a0.h12            NaN  0.000000e+00
14          14    a0.h13      0    a0.h13            NaN  0.000000e+00
15          15    a0.h14      0    a0.h14            NaN  0.000000e+00
16          16    a0.h15      0    a0.h15            NaN  0.000000e+00
17          17    a0.h16      0    a0.h16            NaN  0.000000e+00
18          18    a0.h17      0    a0.h17            NaN  0.000000e+00
19          19    a0.h18      0    a0.h18            NaN  0.000000e+00
20          20    a0.h19      0    a0.h19            NaN  0.000000e+00
21          21    a0.h20      0    a0.h20            NaN  0.000000e+00
22          22    a0.h21      0    a0.h21            NaN  0.000000e+00
23          23    a0.h22      0    a0.h22            NaN  0.000000e+00
24          24    a0.h23      0    a0.h23            NaN  0.000000e+00
25          25    a0.h24      0    a0.h24            NaN  0.000000e+00
26          26    a0.h25      0    a0.h25            NaN  0.000000e+00
27          27    a0.h26      0    a0.h26            NaN  0.000000e+00
28          28    a0.h27      0    a0.h27            NaN  0.000000e+00
29          29    a0.h28      0    a0.h28            NaN  0.000000e+00
30          30    a0.h29      0    a0.h29            NaN  0.000000e+00
31          31    a0.h30      0    a0.h30            NaN  0.000000e+00
32          32    a0.h31      0    a0.h31            NaN  0.000000e+00
33          33        m0      0        m0            NaN -2.486794e-08
34          34    m0.365      0        m0          365.0  4.570456e-03
35          35   m0.3234      0        m0         3234.0  2.728373e-04
36          36   m0.3467      0        m0         3467.0  2.519065e-04
37          37   m0.5769      0        m0         5769.0  0.000000e+00
38          38  m0.10043      0        m0        10043.0  5.100766e-04
39          39     a1.h0      1     a1.h0            NaN  5.034492e-05

In [12]:
sorted_df = subnodes_df.sort_values("score", ascending=False).head(49)
print(sorted_df)

      Unnamed: 0      name  layer node_name  subnode_index     score
1549        1549  m31.8581     31       m31         8581.0  1.510321
1405        1405  m30.9996     30       m30         9996.0  1.103545
527          527       m12     12       m12            NaN  0.726136
1424        1424   a31.h12     31   a31.h12            NaN  0.663149
1339        1339   a30.h10     30   a30.h10            NaN  0.620403
1320        1320  m29.7261     29       m29         7261.0  0.571579
685          685       m16     16       m16            NaN  0.542899
1444        1444       m31     31       m31            NaN  0.520416
981          981       m23     23       m23            NaN  0.467276
1363        1363   m30.732     30       m30          732.0  0.456894
1345        1345   a30.h16     30   a30.h16            NaN  0.377761
1043        1043  m24.7935     24       m24         7935.0  0.374789
1306        1306  m29.4131     29       m29         4131.0  0.373894
566          566       m13     13       m13            NaN  0.350341
1428        1428   a31.h16     31   a31.h16            NaN  0.278034
810          810       m19     19       m19            NaN  0.271658
941          941       m22     22       m22            NaN  0.255033
899          899       m21     21       m21            NaN  0.244954
1070        1070   a25.h23     25   a25.h23            NaN  0.210330
1163        1163    a27.h2     27    a27.h2            NaN  0.207067
1489        1489  m31.3498     31       m31         3498.0  0.193198
1073        1073   a25.h26     25   a25.h26            NaN  0.180264
1047        1047    a25.h0     25    a25.h0            NaN  0.174363
855          855       m20     20       m20            NaN  0.171007
524          524   a12.h29     12   a12.h29            NaN  0.170858
1441        1441   a31.h29     31   a31.h29            NaN  0.167572
1169        1169    a27.h8     27    a27.h8            NaN  0.163530
873          873    a21.h6     21    a21.h6            NaN  0.163375
1102        1102    a26.h3     26    a26.h3            NaN  0.159538
1162        1162    a27.h1     27    a27.h1            NaN  0.151702
1185        1185   a27.h24     27   a27.h24            NaN  0.149668
1165        1165    a27.h4     27    a27.h4            NaN  0.141237
1290        1290   a29.h30     29   a29.h30            NaN  0.135715
1377        1377  m30.3705     30       m30         3705.0  0.114631
1506        1506  m31.4568     31       m31         4568.0  0.114614
1361        1361       m30     30       m30            NaN  0.108805
869          869    a21.h2     21    a21.h2            NaN  0.106263
1078        1078   a25.h31     25   a25.h31            NaN  0.104050
1181        1181   a27.h20     27   a27.h20            NaN  0.098354
1053        1053    a25.h6     25    a25.h6            NaN  0.097493
1430        1430   a31.h18     31   a31.h18            NaN  0.089952
452          452       m10     10       m10            NaN  0.087464
1343        1343   a30.h14     30   a30.h14            NaN  0.086254
720          720   a17.h30     17   a17.h30            NaN  0.085562
1148        1148  m26.5558     26       m26         5558.0  0.085032
398          398    a9.h14      9    a9.h14            NaN  0.082920
1359        1359   a30.h30     30   a30.h30            NaN  0.075203
511          511   a12.h16     12   a12.h16            NaN  0.074649
886          886   a21.h19     21   a21.h19            NaN  0.073845

## Getting the rows we care about

In [12]:
weakening_df = subnodes_df[subnodes_df["subnode_index"].notna()].sort_values("score", ascending=False)
print(weakening_df.shape)

(526, 6)

In [13]:
sorted_filtered_df = weakening_df[weakening_df["score"]>0].sort_values("score", ascending=False)
print(sorted_filtered_df.shape)

(246, 6)

## Inspecting again

In [26]:
print(sorted_filtered_df.head(40))

      Unnamed: 0       name  layer node_name  subnode_index     score
1549        1549   m31.8581     31       m31         8581.0  1.510321
1405        1405   m30.9996     30       m30         9996.0  1.103545
1320        1320   m29.7261     29       m29         7261.0  0.571579
1363        1363    m30.732     30       m30          732.0  0.456894
1043        1043   m24.7935     24       m24         7935.0  0.374789
1306        1306   m29.4131     29       m29         4131.0  0.373894
1489        1489   m31.3498     31       m31         3498.0  0.193198
1377        1377   m30.3705     30       m30         3705.0  0.114631
1506        1506   m31.4568     31       m31         4568.0  0.114614
1148        1148   m26.5558     26       m26         5558.0  0.085032
612          612   m14.4516     14       m14         4516.0  0.066492
1253        1253   m28.6703     28       m28         6703.0  0.039890
1524        1524   m31.5973     31       m31         5973.0  0.037797
1551        1551   m31.8666     31       m31         8666.0  0.037575
1090        1090   m25.6139     25       m25         6139.0  0.027810
1541        1541   m31.7081     31       m31         7081.0  0.024053
1155        1155   m26.6841     26       m26         6841.0  0.023975
1087        1087   m25.4595     25       m25         4595.0  0.014475
1255        1255   m28.8918     28       m28         8918.0  0.009182
1576        1576  m31.10813     31       m31        10813.0  0.008940
1477        1477   m31.2633     31       m31         2633.0  0.008613
1383        1383   m30.4893     30       m30         4893.0  0.008374
1479        1479   m31.2743     31       m31         2743.0  0.008284
211          211    m4.4049      4        m4         4049.0  0.008150
609          609   m14.1849     14       m14         1849.0  0.007953
1552        1552   m31.8839     31       m31         8839.0  0.007830
1526        1526   m31.6064     31       m31         6064.0  0.007653
1530        1530   m31.6312     31       m31         6312.0  0.007480
85            85    m1.6152      1        m1         6152.0  0.007465
904          904   m21.7064     21       m21         7064.0  0.006761
1375        1375   m30.3306     30       m30         3306.0  0.006584
772          772   m18.5914     18       m18         5914.0  0.006181
768          768   m18.3624     18       m18         3624.0  0.006135
568          568   m13.1362     13       m13         1362.0  0.006021
133          133    m2.5267      2        m2         5267.0  0.005834
570          570   m13.1847     13       m13         1847.0  0.005810
989          989   m23.5744     23       m23         5744.0  0.005720
1302        1302   m29.2983     29       m29         2983.0  0.005712
1384        1384   m30.5045     30       m30         5045.0  0.005582
1532        1532   m31.6434     31       m31         6434.0  0.005236

In [27]:
print(sorted_filtered_df.tail(40))

      Unnamed: 0       name  layer node_name  subnode_index     score
382          382      m8.22      8        m8           22.0  0.000156
861          861   m20.1821     20       m20         1821.0  0.000153
208          208     m4.382      4        m4          382.0  0.000143
260          260    m5.6293      5        m5         6293.0  0.000141
1481        1481   m31.2938     31       m31         2938.0  0.000140
1519        1519   m31.5751     31       m31         5751.0  0.000125
1252        1252   m28.6431     28       m28         6431.0  0.000120
129          129    m2.3729      2        m2         3729.0  0.000117
1326        1326  m29.10283     29       m29        10283.0  0.000110
1567        1567  m31.10439     31       m31        10439.0  0.000108
128          128     m2.211      2        m2          211.0  0.000108
1080        1080    m25.782     25       m25          782.0  0.000107
1309        1309   m29.5237     29       m29         5237.0  0.000105
689          689  m16.10972     16       m16        10972.0  0.000099
135          135    m2.6609      2        m2         6609.0  0.000096
1455        1455    m31.738     31       m31          738.0  0.000090
1098        1098  m25.10213     25       m25        10213.0  0.000088
267          267    m5.9824      5        m5         9824.0  0.000088
945          945    m22.336     22       m22          336.0  0.000086
304          304     m6.174      6        m6          174.0  0.000085
453          453   m10.7172     10       m10         7172.0  0.000084
169          169     m3.221      3        m3          221.0  0.000080
1399        1399   m30.8440     30       m30         8440.0  0.000076
1247        1247   m28.3274     28       m28         3274.0  0.000068
731          731   m17.7388     17       m17         7388.0  0.000057
614          614   m14.5588     14       m14         5588.0  0.000056
1317        1317   m29.7052     29       m29         7052.0  0.000056
173          173    m3.7332      3        m3         7332.0  0.000047
1251        1251   m28.5373     28       m28         5373.0  0.000046
987          987   m23.5289     23       m23         5289.0  0.000041
1380        1380   m30.4767     30       m30         4767.0  0.000038
170          170     m3.287      3        m3          287.0  0.000030
73            73     m1.227      1        m1          227.0  0.000027
268          268    m5.9903      5        m5         9903.0  0.000025
265          265    m5.9361      5        m5         9361.0  0.000020
995          995   m23.9611     23       m23         9611.0  0.000018
1154        1154   m26.6642     26       m26         6642.0  0.000016
1517        1517   m31.5489     31       m31         5489.0  0.000010
74            74    m1.1539      1        m1         1539.0  0.000007
1378        1378   m30.4438     30       m30         4438.0  0.000003

In [25]:
weakening_df.tail(40)

      Unnamed: 0       name  layer node_name  subnode_index     score
490          490   m11.1068     11       m11         1068.0 -0.009033
1466        1466   m31.1710     31       m31         1710.0 -0.009061
1366        1366   m30.1511     30       m30         1511.0 -0.009455
1084        1084   m25.2489     25       m25         2489.0 -0.009744
1410        1410  m30.10850     30       m30        10850.0 -0.009938
985          985    m23.513     23       m23          513.0 -0.010247
1404        1404   m30.9656     30       m30         9656.0 -0.010870
1037        1037   m24.2931     24       m24         2931.0 -0.010933
1448        1448    m31.287     31       m31          287.0 -0.011020
1034        1034    m24.619     24       m24          619.0 -0.011640
1546        1546   m31.7718     31       m31         7718.0 -0.012219
346          346    m7.1066      7        m7         1066.0 -0.012382
383          383    m8.4947      8        m8         4947.0 -0.013320
1394        1394   m30.6597     30       m30         6597.0 -0.013352
815          815   m19.4644     19       m19         4644.0 -0.013585
1092        1092   m25.7713     25       m25         7713.0 -0.013902
988          988   m23.5506     23       m23         5506.0 -0.014157
1364        1364    m30.852     30       m30          852.0 -0.014977
1497        1497   m31.4075     31       m31         4075.0 -0.015813
773          773   m18.6799     18       m18         6799.0 -0.022698
488          488    m11.261     11       m11          261.0 -0.024888
214          214    m4.7010      4        m4         7010.0 -0.027290
1194        1194    m27.589     27       m27          589.0 -0.027345
1369        1369   m30.1971     30       m30         1971.0 -0.034160
1095        1095   m25.9227     25       m25         9227.0 -0.034272
1250        1250   m28.5325     28       m28         5325.0 -0.035249
1478        1478   m31.2665     31       m31         2665.0 -0.035805
725          725    m17.820     17       m17          820.0 -0.038827
567          567   m13.1290     13       m13         1290.0 -0.047958
1569        1569  m31.10462     31       m31        10462.0 -0.052168
77            77    m1.2283      1        m1         2283.0 -0.052296
1143        1143   m26.3329     26       m26         3329.0 -0.052487
1381        1381   m30.4810     30       m30         4810.0 -0.058846
419          419   m9.10304      9        m9        10304.0 -0.110668
650          650    m15.446     15       m15          446.0 -0.123251
1241        1241     m28.50     28       m28           50.0 -0.123529
530          530   m12.6695     12       m12         6695.0 -0.129253
215          215    m4.7696      4        m4         7696.0 -0.132217
491          491   m11.2077     11       m11         2077.0 -0.146894
821          821   m19.9428     19       m19         9428.0 -0.247878

## Evaluating via ablations

### General

In [ ]:
model = TransformerBridge.boot_transformers(#with predefined neurons, our ablation code is implementation-invariant
        'allenai/OLMo-7B-0424-hf',
        device=DEVICE,
)
#needed?:
# model.enable_compatibility_mode(
#         no_processing=True
# )

`torch_dtype` is deprecated! Use `dtype` instead!

Loading checkpoint shards:   0%|          | 0/6 [00:00<?, ?it/s]

Loaded pretrained model allenai/OLMo-7B-0424-hf into HookedTransformer

In [15]:
sequence = "Yesterday (21 December) the Government announced a package of support for hospitality and leisure businesses that are losing trade because of the O"

In [16]:
tokens, attention_mask, input_lengths, n_pos = tokenize_plus(model, [sequence])

In [17]:
logits = model(tokens, attention_mask=attention_mask)
score = logits[...,-1,model.to_single_token('mic')].item()
print(score)

21.09280776977539

In [26]:
def run_ablations(args:Namespace, df:pd.DataFrame, score_list:list|None=None, reverse:bool=False):
    if score_list is None:
        score_list = []
    hook_list = []
    if reverse:
        iterator = df[::-1].iterrows()
    else:
        iterator = df.iterrows()
    for i,row in iterator:
        hook_list.extend(
            make_hooks(
                args,
                layer=row["layer"], neuron=int(row["subnode_index"]),
                mean_value=0.0,
            )
        )
        with model.hooks(hook_list):
            logits = model(tokens, attention_mask=attention_mask)
            score = logits[...,-1,model.to_single_token('mic')].item()
            score_list.append(score)
            print(len(score_list), ', ', score)
    return score_list

### Conditional ablations

In [20]:
conditional_args = Namespace(
    gate='-', post='+',
    activation_location='mlp.hook_post',
    intervention_type='zero_ablation',
)

In [21]:
conditional_score_list = run_ablations(conditional_args, weakening_df)

0 ,  21.100914001464844
1 ,  19.696533203125
2 ,  18.707666397094727
3 ,  17.81782341003418
4 ,  16.941997528076172
5 ,  15.728752136230469
6 ,  15.728752136230469
7 ,  15.550999641418457
8 ,  15.550999641418457
9 ,  14.758160591125488
10 ,  14.822168350219727
11 ,  12.08298110961914
12 ,  12.08298110961914
13 ,  12.07059097290039
14 ,  9.4954833984375
15 ,  9.4954833984375
16 ,  9.234922409057617
17 ,  9.234922409057617
18 ,  9.20826244354248
19 ,  9.20826244354248
20 ,  9.20826244354248
21 ,  9.20826244354248
22 ,  9.20826244354248
23 ,  9.213786125183105
24 ,  9.215871810913086
25 ,  9.215871810913086
26 ,  9.215871810913086
27 ,  9.215871810913086
28 ,  9.206403732299805
29 ,  9.214556694030762
30 ,  9.210439682006836
31 ,  9.208571434020996
32 ,  9.208571434020996
33 ,  9.208826065063477
34 ,  9.22209358215332
35 ,  9.22209358215332
36 ,  9.22011661529541
37 ,  9.22011661529541
38 ,  9.220125198364258
39 ,  9.220125198364258
40 ,  9.195072174072266
41 ,  9.192594528198242
42 ,  9.170336723327637
43 ,  9.170336723327637
44 ,  9.170336723327637
45 ,  9.113377571105957
46 ,  9.113377571105957
47 ,  9.118020057678223
48 ,  9.117417335510254
49 ,  9.118200302124023
50 ,  9.118200302124023
51 ,  9.118200302124023
52 ,  9.121480941772461
53 ,  9.121480941772461
54 ,  9.121480941772461
55 ,  9.121349334716797
56 ,  9.121135711669922
57 ,  9.121135711669922
58 ,  9.12140941619873
59 ,  9.12140941619873
60 ,  9.015968322753906
61 ,  9.02581787109375
62 ,  9.024965286254883
63 ,  8.806625366210938
64 ,  8.806625366210938
65 ,  8.806625366210938
66 ,  7.3902363777160645
67 ,  7.3902363777160645
68 ,  7.263814926147461
69 ,  7.263814926147461
70 ,  7.263814926147461
71 ,  7.208600997924805
72 ,  7.208600997924805
73 ,  7.208554267883301
74 ,  7.208554267883301
75 ,  7.208554267883301
76 ,  7.208919525146484
77 ,  7.208919525146484
78 ,  7.208919525146484
79 ,  7.209355354309082
80 ,  7.209355354309082
81 ,  7.20961856842041
82 ,  7.20961856842041
83 ,  7.20961856842041
84 ,  7.2117815017700195
85 ,  7.20927619934082
86 ,  7.224268436431885
87 ,  7.224268436431885
88 ,  7.223697662353516
89 ,  7.223697662353516
90 ,  7.223697662353516
91 ,  7.223751068115234
92 ,  7.223751068115234
93 ,  7.223749160766602
94 ,  7.223749160766602
95 ,  7.223978042602539
96 ,  7.223978042602539
97 ,  7.2215471267700195
98 ,  7.2215471267700195
99 ,  7.221100807189941
100 ,  7.221100807189941
101 ,  7.221100807189941
102 ,  7.220606803894043
103 ,  7.220604419708252
104 ,  7.220604419708252
105 ,  7.220604419708252
106 ,  7.220604419708252
107 ,  7.229973316192627
108 ,  7.22996711730957
109 ,  7.230315208435059
110 ,  7.230315208435059
111 ,  7.228266716003418
112 ,  7.228019714355469
113 ,  7.228019714355469
114 ,  7.228019714355469
115 ,  7.234890460968018
116 ,  7.237303256988525
117 ,  7.237329483032227
118 ,  7.2375030517578125
119 ,  7.2375030517578125
120 ,  7.234944820404053
121 ,  7.234944820404053
122 ,  7.234944820404053
123 ,  7.230791091918945
124 ,  7.236639976501465
125 ,  7.236639976501465
126 ,  7.227734565734863
127 ,  7.227734565734863
128 ,  7.232165813446045
129 ,  7.232165813446045
130 ,  7.232048988342285
131 ,  7.232048988342285
132 ,  7.232319355010986
133 ,  7.232661724090576
134 ,  7.204113006591797
135 ,  7.204113006591797
136 ,  7.19991397857666
137 ,  7.19991397857666
138 ,  7.19991397857666
139 ,  7.200503826141357
140 ,  7.200503826141357
141 ,  7.201421737670898
142 ,  7.201421737670898
143 ,  7.201421737670898
144 ,  7.201421737670898
145 ,  7.20114803314209
146 ,  7.20114803314209
147 ,  7.1991868019104
148 ,  7.199188709259033
149 ,  7.124468803405762
150 ,  7.124241828918457
151 ,  7.120075702667236
152 ,  7.120075702667236
153 ,  7.111520767211914
154 ,  7.1112470626831055
155 ,  7.1112470626831055
156 ,  7.1112470626831055
157 ,  7.109289646148682
158 ,  7.109289646148682
159 ,  7.104940414428711
160 ,  7.104940414428711
161 ,  7.10496711730957
162 ,  7.105926990509033
163 ,  7.105760097503662
164 ,  7.103184700012207
165 ,  7.113097190856934
166 ,  7.113097190856934
167 ,  7.112684726715088
168 ,  7.112684726715088
169 ,  7.112684726715088
170 ,  7.109567165374756
171 ,  7.106155872344971
172 ,  7.106155872344971
173 ,  7.1061811447143555
174 ,  7.105151176452637
175 ,  7.105151176452637
176 ,  7.10493278503418
177 ,  7.105151176452637
178 ,  7.104897499084473
179 ,  7.10488224029541
180 ,  7.100313663482666
181 ,  7.100196838378906
182 ,  7.100196838378906
183 ,  7.100196838378906
184 ,  7.100773811340332
185 ,  7.100773811340332
186 ,  7.100981712341309
187 ,  7.100981712341309
188 ,  7.100981712341309
189 ,  7.1078572273254395
190 ,  7.107545852661133
191 ,  7.107545852661133
192 ,  7.104061126708984
193 ,  7.104061126708984
194 ,  7.104061126708984
195 ,  7.109125137329102
196 ,  7.10930061340332
197 ,  7.10930061340332
198 ,  7.108649253845215
199 ,  7.108649253845215
200 ,  7.103443145751953
201 ,  7.103431224822998
202 ,  7.103466987609863
203 ,  7.1034674644470215
204 ,  7.103488445281982
205 ,  7.103488445281982
206 ,  7.103610038757324
207 ,  7.103579998016357
208 ,  7.103579998016357
209 ,  7.101613998413086
210 ,  7.101613998413086
211 ,  7.101613998413086
212 ,  7.101613998413086
213 ,  7.101673126220703
214 ,  7.101129531860352
215 ,  7.101129531860352
216 ,  7.101605415344238
217 ,  7.101566791534424
218 ,  7.101468086242676
219 ,  7.101468086242676
220 ,  7.101468086242676
221 ,  7.101468086242676
222 ,  7.103194236755371
223 ,  7.103367805480957
224 ,  7.102587699890137
225 ,  7.103740215301514
226 ,  7.103740215301514
227 ,  7.103753089904785
228 ,  7.103673458099365
229 ,  7.103837013244629
230 ,  7.103837013244629
231 ,  7.103837013244629
232 ,  7.103825092315674
233 ,  7.103942394256592
234 ,  7.103942394256592
235 ,  7.103942394256592
236 ,  7.103942394256592
237 ,  7.104211807250977
238 ,  7.104211807250977
239 ,  7.104211807250977
240 ,  7.104211807250977
241 ,  7.104307174682617
242 ,  7.104304313659668
243 ,  7.104304313659668
244 ,  7.1041998863220215
245 ,  7.1041998863220215
246 ,  7.1041998863220215
247 ,  7.1041998863220215
248 ,  7.104133129119873
249 ,  7.103107452392578
250 ,  7.103107452392578
251 ,  7.103107452392578
252 ,  7.103107452392578
253 ,  7.103107452392578
254 ,  7.103051662445068
255 ,  7.100749969482422
256 ,  7.101408958435059
257 ,  7.101408958435059
258 ,  7.101408958435059
259 ,  7.101408958435059
260 ,  7.101408958435059
261 ,  7.101408958435059
262 ,  7.101408958435059
263 ,  7.101408958435059
264 ,  7.101408958435059
265 ,  7.101413726806641
266 ,  7.101413726806641
267 ,  7.101413726806641
268 ,  7.101413726806641
269 ,  7.101413726806641
270 ,  7.101413726806641
271 ,  7.101413726806641
272 ,  7.101413726806641
273 ,  7.101365089416504
274 ,  7.101163864135742
275 ,  7.101163864135742
276 ,  7.1015424728393555
277 ,  7.101875305175781
278 ,  7.101804733276367
279 ,  7.101804733276367
280 ,  7.0980119705200195
281 ,  7.0980119705200195
282 ,  7.098081111907959
283 ,  7.098081111907959
284 ,  7.0976786613464355
285 ,  7.0976104736328125
286 ,  7.097966194152832
287 ,  7.097966194152832
288 ,  7.097966194152832
289 ,  7.097966194152832
290 ,  7.097966194152832
291 ,  7.098066806793213
292 ,  7.097031593322754
293 ,  7.096208572387695
294 ,  7.096796035766602
295 ,  7.097729682922363
296 ,  7.097729682922363
297 ,  7.097603797912598
298 ,  7.097603797912598
299 ,  7.097603797912598
300 ,  7.099755764007568
301 ,  7.099755764007568
302 ,  7.100490570068359
303 ,  7.100490570068359
304 ,  7.100424766540527
305 ,  7.100424766540527
306 ,  7.100424766540527
307 ,  7.100424766540527
308 ,  7.100985050201416
309 ,  7.101166725158691
310 ,  7.100833415985107
311 ,  7.100833415985107
312 ,  7.100833415985107
313 ,  7.100848197937012
314 ,  7.112395763397217
315 ,  7.112395763397217
316 ,  7.112395763397217
317 ,  7.112357139587402
318 ,  7.112357139587402
319 ,  7.126463413238525
320 ,  7.1217041015625
321 ,  7.1217041015625
322 ,  7.122690677642822
323 ,  7.122690677642822
324 ,  7.122690677642822
325 ,  7.122690677642822
326 ,  7.087450981140137
327 ,  7.087450981140137
328 ,  7.08780574798584
329 ,  7.086973190307617
330 ,  7.086973190307617
331 ,  7.086973190307617
332 ,  7.0860490798950195
333 ,  7.086495399475098
334 ,  7.086495399475098
335 ,  7.085999488830566
336 ,  7.085475921630859
337 ,  7.085475921630859
338 ,  7.085475921630859
339 ,  7.08455753326416
340 ,  7.08455753326416
341 ,  7.086261749267578
342 ,  7.105197429656982
343 ,  7.108891010284424
344 ,  7.130430221557617
345 ,  7.130430221557617
346 ,  7.121871471405029
347 ,  7.127995491027832
348 ,  7.127995491027832
349 ,  7.127995491027832
350 ,  7.127995491027832
351 ,  7.1314778327941895
352 ,  7.1314778327941895
353 ,  7.12962532043457
354 ,  7.12962532043457
355 ,  7.125483512878418
356 ,  7.125483512878418
357 ,  7.125483512878418
358 ,  7.127989292144775
359 ,  7.129311561584473
360 ,  7.129311561584473
361 ,  7.129311561584473
362 ,  7.129311561584473
363 ,  7.127020835876465
364 ,  7.125095844268799
365 ,  7.1267900466918945
366 ,  7.1267900466918945
367 ,  7.138885498046875
368 ,  7.138885498046875
369 ,  7.138885498046875
370 ,  7.138885498046875
371 ,  7.138885498046875
372 ,  7.13878059387207
373 ,  7.138825416564941
374 ,  7.138976573944092
375 ,  7.139616966247559
376 ,  7.139766693115234
377 ,  7.140109062194824
378 ,  7.140109062194824
379 ,  7.140109062194824
380 ,  7.140166282653809
381 ,  7.140166282653809
382 ,  7.140166282653809
383 ,  7.140166282653809
384 ,  7.140166282653809
385 ,  7.137876033782959
386 ,  7.138686656951904
387 ,  7.135538101196289
388 ,  7.135538101196289
389 ,  7.135538101196289
390 ,  7.141784191131592
391 ,  7.141784191131592
392 ,  7.141784191131592
393 ,  7.141784191131592
394 ,  7.142845630645752
395 ,  7.144695281982422
396 ,  7.14626407623291
397 ,  7.156879425048828
398 ,  7.180849075317383
399 ,  7.180849075317383
400 ,  7.1797027587890625
401 ,  7.1797027587890625
402 ,  7.179649829864502
403 ,  7.180012226104736
404 ,  7.180012226104736
405 ,  7.179521083831787
406 ,  7.188540458679199
407 ,  7.188540458679199
408 ,  7.187832832336426
409 ,  7.1881279945373535
410 ,  7.1881279945373535
411 ,  7.1881279945373535
412 ,  7.1881279945373535
413 ,  7.188148498535156
414 ,  7.188148498535156
415 ,  7.188514709472656
416 ,  7.188448905944824
417 ,  7.179290771484375
418 ,  7.179144859313965
419 ,  7.175295352935791
420 ,  7.176645278930664
421 ,  7.1780686378479
422 ,  7.1780686378479
423 ,  7.17836856842041
424 ,  7.187859535217285
425 ,  7.1878557205200195
426 ,  7.206146717071533
427 ,  7.20878791809082
428 ,  7.202413558959961
429 ,  7.202413558959961
430 ,  7.18654727935791
431 ,  7.18651008605957
432 ,  7.18651008605957
433 ,  7.18651008605957
434 ,  7.209687232971191
435 ,  7.209687232971191
436 ,  7.209687232971191
437 ,  7.209687232971191
438 ,  7.209588527679443
439 ,  7.209400653839111
440 ,  7.209400653839111
441 ,  7.20914363861084
442 ,  7.209307670593262
443 ,  7.209307670593262
444 ,  7.209307670593262
445 ,  7.209307670593262
446 ,  7.209307670593262
447 ,  7.209307670593262
448 ,  7.209307670593262
449 ,  7.209250450134277
450 ,  7.216754913330078
451 ,  7.216754913330078
452 ,  7.216754913330078
453 ,  7.21173620223999
454 ,  7.21173620223999
455 ,  7.21173620223999
456 ,  7.2108917236328125
457 ,  7.2108917236328125
458 ,  7.2108917236328125
459 ,  7.210513114929199
460 ,  7.210518836975098
461 ,  7.210518836975098
462 ,  7.210986614227295
463 ,  7.210705757141113
464 ,  7.210705757141113
465 ,  7.209742069244385
466 ,  7.20831823348999
467 ,  7.20831823348999
468 ,  7.20831823348999
469 ,  7.208336353302002
470 ,  7.202608108520508
471 ,  7.202608108520508
472 ,  7.2030029296875
473 ,  7.2030029296875
474 ,  7.152347564697266
475 ,  7.15590763092041
476 ,  7.1559343338012695
477 ,  7.158333778381348
478 ,  7.161441802978516
479 ,  7.161441802978516
480 ,  7.107041358947754
481 ,  7.106349945068359
482 ,  7.106349945068359
483 ,  7.106349945068359
484 ,  7.106349945068359
485 ,  7.106349945068359
486 ,  7.106450080871582
487 ,  7.106450080871582
488 ,  7.106450080871582
489 ,  7.228292465209961
490 ,  7.228292465209961
491 ,  7.121218204498291
492 ,  7.121149063110352
493 ,  7.121149063110352
494 ,  7.121149063110352
495 ,  7.071834564208984
496 ,  7.071834564208984
497 ,  7.099592208862305
498 ,  7.054345607757568
499 ,  7.055248260498047
500 ,  7.057708740234375
501 ,  7.054201126098633
502 ,  7.077259540557861
503 ,  7.077369689941406
504 ,  7.077369689941406
505 ,  7.077369689941406
506 ,  7.1182403564453125
507 ,  7.099320411682129
508 ,  7.09365177154541
509 ,  7.096283435821533
510 ,  7.017332077026367
511 ,  7.019099712371826
512 ,  7.0229902267456055
513 ,  7.025268077850342
514 ,  7.096479892730713
515 ,  7.096479892730713
516 ,  7.197440147399902
517 ,  7.558035850524902
518 ,  7.558035850524902
519 ,  7.181726455688477
520 ,  7.185032844543457
521 ,  7.254092693328857
522 ,  6.114618301391602
523 ,  6.120294570922852
524 ,  6.028684616088867
525 ,  1.1676186323165894

### How about non-conditional ablations?

In [23]:
unconditional_args = Namespace(
    gate=None, post=None,
    activation_location='mlp.hook_post',
    intervention_type='zero_ablation',
)

In [24]:
unconditional_score_list = run_ablations(unconditional_args, weakening_df)

1 ,  21.100914001464844
2 ,  19.676048278808594
3 ,  18.67130470275879
4 ,  17.786930084228516
5 ,  16.908519744873047
6 ,  15.697864532470703
7 ,  15.514573097229004
8 ,  15.350500106811523
9 ,  15.177751541137695
10 ,  14.407808303833008
11 ,  14.552196502685547
12 ,  12.199928283691406
13 ,  12.202348709106445
14 ,  12.191187858581543
15 ,  9.844694137573242
16 ,  9.841757774353027
17 ,  9.552042007446289
18 ,  9.1091890335083
19 ,  9.116903305053711
20 ,  9.107412338256836
21 ,  9.107223510742188
22 ,  9.129350662231445
23 ,  9.126296997070312
24 ,  9.133541107177734
25 ,  9.134151458740234
26 ,  9.129873275756836
27 ,  9.130594253540039
28 ,  9.129091262817383
29 ,  9.131183624267578
30 ,  9.147056579589844
31 ,  9.140364646911621
32 ,  9.126411437988281
33 ,  9.113723754882812
34 ,  9.112071990966797
35 ,  9.145425796508789
36 ,  9.177021026611328
37 ,  9.139070510864258
38 ,  9.018017768859863
39 ,  9.023193359375
40 ,  9.022941589355469
41 ,  8.991870880126953
42 ,  9.10708999633789
43 ,  9.080997467041016
44 ,  9.08016586303711
45 ,  9.151206970214844
46 ,  9.075349807739258
47 ,  9.073005676269531
48 ,  9.062858581542969
49 ,  9.049383163452148
50 ,  8.99930191040039
51 ,  9.019022941589355
52 ,  9.050125122070312
53 ,  9.088417053222656
54 ,  9.08319091796875
55 ,  9.082460403442383
56 ,  9.134164810180664
57 ,  9.140216827392578
58 ,  9.138808250427246
59 ,  9.126367568969727
60 ,  9.124090194702148
61 ,  9.031896591186523
62 ,  9.093250274658203
63 ,  8.989630699157715
64 ,  8.75467300415039
65 ,  8.750811576843262
66 ,  8.751511573791504
67 ,  7.517806529998779
68 ,  7.528475284576416
69 ,  7.538362503051758
70 ,  7.523296356201172
71 ,  7.523322105407715
72 ,  7.483336448669434
73 ,  7.485251426696777
74 ,  7.473837852478027
75 ,  7.474631309509277
76 ,  7.484632968902588
77 ,  7.48123836517334
78 ,  7.4825286865234375
79 ,  7.481868743896484
80 ,  7.477225303649902
81 ,  7.4757981300354
82 ,  7.476949691772461
83 ,  7.475266933441162
84 ,  7.4752302169799805
85 ,  7.475485801696777
86 ,  7.473752021789551
87 ,  7.4867753982543945
88 ,  7.471637725830078
89 ,  7.466549873352051
90 ,  7.477140426635742
91 ,  7.477007865905762
92 ,  7.463769912719727
93 ,  7.463708877563477
94 ,  7.4647016525268555
95 ,  7.4641876220703125
96 ,  7.402348518371582
97 ,  7.402155876159668
98 ,  7.39909553527832
99 ,  7.403037071228027
100 ,  7.405138969421387
101 ,  7.404919624328613
102 ,  7.392220497131348
103 ,  7.392844200134277
104 ,  7.396397590637207
105 ,  7.397628307342529
106 ,  7.3975934982299805
107 ,  7.397043228149414
108 ,  7.399125576019287
109 ,  7.406693458557129
110 ,  7.407573699951172
111 ,  7.402768611907959
112 ,  7.3906965255737305
113 ,  7.390995025634766
114 ,  7.3908610343933105
115 ,  7.390754699707031
116 ,  7.39085578918457
117 ,  7.393257141113281
118 ,  7.3952531814575195
119 ,  7.394529342651367
120 ,  7.394418716430664
121 ,  7.393712520599365
122 ,  7.398179054260254
123 ,  7.401103973388672
124 ,  7.393976211547852
125 ,  7.397783279418945
126 ,  7.399625778198242
127 ,  7.3894734382629395
128 ,  7.3894429206848145
129 ,  7.390142917633057
130 ,  7.39000940322876
131 ,  7.390093803405762
132 ,  7.396821022033691
133 ,  7.397332668304443
134 ,  7.397430896759033
135 ,  7.3870062828063965
136 ,  7.386929512023926
137 ,  7.38023042678833
138 ,  7.37911319732666
139 ,  7.3779988288879395
140 ,  7.3986406326293945
141 ,  7.398190498352051
142 ,  7.316184997558594
143 ,  7.296964645385742
144 ,  7.296972274780273
145 ,  7.292715072631836
146 ,  7.294499397277832
147 ,  7.294229507446289
148 ,  7.308187484741211
149 ,  7.3081560134887695
150 ,  7.289666175842285
151 ,  7.2913432121276855
152 ,  7.2841081619262695
153 ,  7.283742904663086
154 ,  7.283712387084961
155 ,  7.2935943603515625
156 ,  7.293402671813965
157 ,  7.288570404052734
158 ,  7.2773871421813965
159 ,  7.276674270629883
160 ,  7.281289100646973
161 ,  7.281428337097168
162 ,  7.2814621925354
163 ,  7.282204627990723
164 ,  7.291955947875977
165 ,  7.288298606872559
166 ,  7.290596961975098
167 ,  7.282780647277832
168 ,  7.2807087898254395
169 ,  7.277773857116699
170 ,  7.277713775634766
171 ,  7.275866508483887
172 ,  7.283970832824707
173 ,  7.286956787109375
174 ,  7.281446933746338
175 ,  7.291804313659668
176 ,  7.291834354400635
177 ,  7.293503284454346
178 ,  7.295366287231445
179 ,  7.344925880432129
180 ,  7.348629951477051
181 ,  7.345685005187988
182 ,  7.342968940734863
183 ,  7.342891693115234
184 ,  7.342909812927246
185 ,  7.358238220214844
186 ,  7.360962867736816
187 ,  7.361981391906738
188 ,  7.362033367156982
189 ,  7.3596601486206055
190 ,  7.367100238800049
191 ,  7.370136260986328
192 ,  7.370070457458496
193 ,  7.39892578125
194 ,  7.3974690437316895
195 ,  7.396010398864746
196 ,  7.397781848907471
197 ,  7.393668174743652
198 ,  7.393362045288086
199 ,  7.399190425872803
200 ,  7.337204933166504
201 ,  7.328063011169434
202 ,  7.32505989074707
203 ,  7.325270652770996
204 ,  7.325256824493408
205 ,  7.325859546661377
206 ,  7.325833320617676
207 ,  7.321369647979736
208 ,  7.32651948928833
209 ,  7.327589988708496
210 ,  7.323472023010254
211 ,  7.323954105377197
212 ,  7.323637962341309
213 ,  7.332650661468506
214 ,  7.343613624572754
215 ,  7.339916229248047
216 ,  7.339902877807617
217 ,  7.339292526245117
218 ,  7.338037014007568
219 ,  7.340773582458496
220 ,  7.3383378982543945
221 ,  7.339478492736816
222 ,  7.338934421539307
223 ,  7.325407981872559
224 ,  7.3231964111328125
225 ,  7.326040267944336
226 ,  7.323722839355469
227 ,  7.315712928771973
228 ,  7.28593111038208
229 ,  7.285940170288086
230 ,  7.2804412841796875
231 ,  7.286457061767578
232 ,  7.277772903442383
233 ,  7.259308338165283
234 ,  7.259320259094238
235 ,  7.255606651306152
236 ,  7.255484104156494
237 ,  7.254955291748047
238 ,  7.248224258422852
239 ,  7.213362216949463
240 ,  7.214881896972656
241 ,  7.2138352394104
242 ,  7.212163925170898
243 ,  7.186808109283447
244 ,  7.187831878662109
245 ,  7.197936058044434
246 ,  7.195409774780273
247 ,  7.1860127449035645
248 ,  7.186013221740723
249 ,  7.195351600646973
250 ,  7.172607421875
251 ,  7.171098709106445
252 ,  7.170753002166748
253 ,  7.158656597137451
254 ,  7.158353805541992
255 ,  7.146965503692627
256 ,  7.148377895355225
257 ,  7.146797180175781
258 ,  7.146660804748535
259 ,  7.148556232452393
260 ,  7.147950649261475
261 ,  7.147994518280029
262 ,  7.150794982910156
263 ,  7.1497063636779785
264 ,  7.149661064147949
265 ,  7.123802185058594
266 ,  7.1235432624816895
267 ,  7.124998092651367
268 ,  7.125121593475342
269 ,  7.117494583129883
270 ,  7.117489814758301
271 ,  7.117405414581299
272 ,  7.11700439453125
273 ,  7.116867542266846
274 ,  7.116659164428711
275 ,  7.118021488189697
276 ,  7.11801290512085
277 ,  7.121242523193359
278 ,  7.1277289390563965
279 ,  7.129061698913574
280 ,  7.128795623779297
281 ,  7.124696254730225
282 ,  7.124795913696289
283 ,  7.122392177581787
284 ,  7.122417449951172
285 ,  7.134041786193848
286 ,  7.118931770324707
287 ,  7.108255863189697
288 ,  7.109704494476318
289 ,  7.109699726104736
290 ,  7.110116958618164
291 ,  7.10993766784668
292 ,  7.104495525360107
293 ,  7.103650093078613
294 ,  7.099538803100586
295 ,  7.097493648529053
296 ,  7.097238540649414
297 ,  7.090421676635742
298 ,  7.087953567504883
299 ,  7.088953018188477
300 ,  7.087258815765381
301 ,  7.08663272857666
302 ,  7.0865583419799805
303 ,  7.084421634674072
304 ,  7.084205150604248
305 ,  7.088540077209473
306 ,  7.088747024536133
307 ,  7.088956832885742
308 ,  7.089075565338135
309 ,  7.050166130065918
310 ,  7.087007522583008
311 ,  7.073224067687988
312 ,  7.074026107788086
313 ,  7.072502136230469
314 ,  7.072629451751709
315 ,  7.0707292556762695
316 ,  7.071243762969971
317 ,  7.07144021987915
318 ,  7.066534996032715
319 ,  7.066375732421875
320 ,  7.071758270263672
321 ,  7.069452285766602
322 ,  7.069446563720703
323 ,  7.058759689331055
324 ,  7.058926105499268
325 ,  7.060478210449219
326 ,  7.0610432624816895
327 ,  7.055471420288086
328 ,  7.055873394012451
329 ,  7.0543622970581055
330 ,  7.056079864501953
331 ,  7.05527400970459
332 ,  7.059659957885742
333 ,  7.054620742797852
334 ,  7.059575080871582
335 ,  7.0595831871032715
336 ,  7.063289642333984
337 ,  7.067373275756836
338 ,  7.06736946105957
339 ,  7.045366287231445
340 ,  7.045388221740723
341 ,  7.045586109161377
342 ,  7.039180278778076
343 ,  7.041860580444336
344 ,  7.043774604797363
345 ,  7.056667327880859
346 ,  7.051890850067139
347 ,  7.050642967224121
348 ,  7.061300754547119
349 ,  7.062314987182617
350 ,  7.062320709228516
351 ,  7.061619758605957
352 ,  7.061600208282471
353 ,  7.064584732055664
354 ,  7.053526878356934
355 ,  7.053069591522217
356 ,  7.048720359802246
357 ,  7.0670342445373535
358 ,  7.067258834838867
359 ,  7.0698652267456055
360 ,  7.059413909912109
361 ,  7.059270858764648
362 ,  7.059402942657471
363 ,  7.072979927062988
364 ,  7.080633163452148
365 ,  7.076224327087402
366 ,  7.081291675567627
367 ,  7.080970764160156
368 ,  7.0880351066589355
369 ,  7.088905334472656
370 ,  7.088904857635498
371 ,  7.088973045349121
372 ,  7.091015338897705
373 ,  7.091017246246338
374 ,  7.090505599975586
375 ,  7.0734357833862305
376 ,  7.070662498474121
377 ,  7.06707239151001
378 ,  7.065629482269287
379 ,  7.06626033782959
380 ,  7.069204807281494
381 ,  7.069240570068359
382 ,  7.069038391113281
383 ,  7.072373867034912
384 ,  6.99602746963501
385 ,  7.006821632385254
386 ,  7.004626750946045
387 ,  6.94766902923584
388 ,  6.94361686706543
389 ,  6.943367958068848
390 ,  6.943537712097168
391 ,  6.946173667907715
392 ,  6.946102142333984
393 ,  6.945769309997559
394 ,  6.943839073181152
395 ,  6.9339599609375
396 ,  6.937051773071289
397 ,  6.935358047485352
398 ,  6.935547828674316
399 ,  6.938633441925049
400 ,  6.938635349273682
401 ,  6.938238143920898
402 ,  6.938252925872803
403 ,  6.938887596130371
404 ,  6.93903112411499
405 ,  6.938628196716309
406 ,  6.939265251159668
407 ,  6.939664840698242
408 ,  6.925275802612305
409 ,  6.950573921203613
410 ,  6.944781303405762
411 ,  6.944276809692383
412 ,  6.944322109222412
413 ,  6.944232940673828
414 ,  6.941921234130859
415 ,  6.941729545593262
416 ,  6.9419660568237305
417 ,  6.941667556762695
418 ,  6.929444313049316
419 ,  6.920888900756836
420 ,  6.909184455871582
421 ,  6.910712242126465
422 ,  6.912280559539795
423 ,  6.912397384643555
424 ,  6.916778087615967
425 ,  6.909970760345459
426 ,  6.917235374450684
427 ,  6.933292388916016
428 ,  6.93843936920166
429 ,  6.936059474945068
430 ,  6.938785552978516
431 ,  6.932653903961182
432 ,  6.930999755859375
433 ,  6.950628757476807
434 ,  6.9497857093811035
435 ,  6.944940567016602
436 ,  6.945023536682129
437 ,  6.945568561553955
438 ,  6.945106506347656
439 ,  6.946428298950195
440 ,  6.945707321166992
441 ,  6.947460174560547
442 ,  6.941236972808838
443 ,  6.944703102111816
444 ,  6.944823741912842
445 ,  6.944475173950195
446 ,  6.944614887237549
447 ,  6.944607734680176
448 ,  6.947704315185547
449 ,  6.947775840759277
450 ,  6.942244052886963
451 ,  6.940335750579834
452 ,  6.942563056945801
453 ,  6.9427103996276855
454 ,  6.941353797912598
455 ,  6.935717582702637
456 ,  6.935694694519043
457 ,  6.933502197265625
458 ,  6.933983325958252
459 ,  6.935050010681152
460 ,  6.936033248901367
461 ,  6.934589385986328
462 ,  6.932263374328613
463 ,  6.8314008712768555
464 ,  6.830240249633789
465 ,  6.840157508850098
466 ,  6.843414306640625
467 ,  6.835519790649414
468 ,  6.835736274719238
469 ,  6.836233139038086
470 ,  6.839707851409912
471 ,  6.837762355804443
472 ,  6.837900638580322
473 ,  6.835931777954102
474 ,  6.826223850250244
475 ,  6.828478813171387
476 ,  6.820660591125488
477 ,  6.796878337860107
478 ,  6.802350997924805
479 ,  6.804709434509277
480 ,  6.805509567260742
481 ,  6.789235591888428
482 ,  6.792267322540283
483 ,  6.795489311218262
484 ,  6.7957377433776855
485 ,  6.79398250579834
486 ,  6.785215377807617
487 ,  6.781702518463135
488 ,  6.780229091644287
489 ,  6.780123233795166
490 ,  6.77731990814209
491 ,  6.774754047393799
492 ,  6.738188743591309
493 ,  6.741355895996094
494 ,  6.74318790435791
495 ,  6.743664741516113
496 ,  6.746633052825928
497 ,  6.747379302978516
498 ,  6.7582106590271
499 ,  6.668964862823486
500 ,  6.66115665435791
501 ,  6.620779991149902
502 ,  6.6213788986206055
503 ,  6.629595756530762
504 ,  6.627357006072998
505 ,  6.628209114074707
506 ,  5.788026809692383
507 ,  5.8960280418396
508 ,  5.825606346130371
509 ,  6.043140411376953
510 ,  6.049862861633301
511 ,  6.023646354675293
512 ,  3.2257635593414307
513 ,  3.225952625274658
514 ,  3.225416898727417
515 ,  3.6040570735931396
516 ,  3.6044039726257324
517 ,  3.731254816055298
518 ,  4.78924560546875
519 ,  4.879196643829346
520 ,  4.114439010620117
521 ,  6.528761863708496
522 ,  6.608940124511719
523 ,  1.0458226203918457
524 ,  0.9241717457771301
525 ,  0.568591296672821
526 ,  -0.24615958333015442

### How about reversing the order?

In [27]:
reversed_unconditional_score_list = run_ablations(unconditional_args, weakening_df, reverse=True)

1 ,  21.187631607055664
2 ,  21.18760871887207
3 ,  21.32521629333496
4 ,  21.392553329467773
5 ,  21.497812271118164
6 ,  20.80942726135254
7 ,  20.47566795349121
8 ,  20.83644676208496
9 ,  20.869461059570312
10 ,  20.927759170532227
11 ,  20.96639633178711
12 ,  21.03947639465332
13 ,  20.996511459350586
14 ,  21.02628517150879
15 ,  20.87240219116211
16 ,  20.888755798339844
17 ,  20.930601119995117
18 ,  20.927644729614258
19 ,  20.912261962890625
20 ,  20.96051597595215
21 ,  20.47476577758789
22 ,  20.479270935058594
23 ,  20.468238830566406
24 ,  20.49325942993164
25 ,  20.487550735473633
26 ,  20.325393676757812
27 ,  20.309423446655273
28 ,  20.107038497924805
29 ,  20.128925323486328
30 ,  20.140384674072266
31 ,  20.217620849609375
32 ,  20.22705078125
33 ,  20.231624603271484
34 ,  20.226749420166016
35 ,  20.253429412841797
36 ,  20.254255294799805
37 ,  20.284706115722656
38 ,  20.285686492919922
39 ,  20.29203987121582
40 ,  20.294017791748047
41 ,  20.286739349365234
42 ,  20.285980224609375
43 ,  20.295682907104492
44 ,  20.293148040771484
45 ,  20.299243927001953
46 ,  20.293262481689453
47 ,  20.296794891357422
48 ,  20.282466888427734
49 ,  20.286773681640625
50 ,  20.26573944091797
51 ,  20.248369216918945
52 ,  20.225955963134766
53 ,  20.20520782470703
54 ,  20.210683822631836
55 ,  20.213272094726562
56 ,  20.213314056396484
57 ,  20.213207244873047
58 ,  20.218856811523438
59 ,  20.221546173095703
60 ,  20.207046508789062
61 ,  20.20859718322754
62 ,  20.203996658325195
63 ,  20.203407287597656
64 ,  20.135711669921875
65 ,  20.139921188354492
66 ,  20.15713882446289
67 ,  20.182512283325195
68 ,  20.184276580810547
69 ,  20.183109283447266
70 ,  20.185096740722656
71 ,  20.185205459594727
72 ,  20.18651008605957
73 ,  20.190765380859375
74 ,  20.19138526916504
75 ,  20.193912506103516
76 ,  20.18822479248047
77 ,  20.168468475341797
78 ,  20.173511505126953
79 ,  20.17589569091797
80 ,  20.179515838623047
81 ,  20.18187141418457
82 ,  20.18448829650879
83 ,  20.18561553955078
84 ,  20.16994857788086
85 ,  20.168964385986328
86 ,  20.170379638671875
87 ,  20.172237396240234
88 ,  20.173492431640625
89 ,  20.17418670654297
90 ,  20.176422119140625
91 ,  20.17637825012207
92 ,  20.1861515045166
93 ,  20.186290740966797
94 ,  20.19093132019043
95 ,  20.17989730834961
96 ,  20.174074172973633
97 ,  20.177845001220703
98 ,  20.199695587158203
99 ,  20.205821990966797
100 ,  20.208812713623047
101 ,  20.209863662719727
102 ,  20.22625732421875
103 ,  20.222082138061523
104 ,  20.22186279296875
105 ,  20.226612091064453
106 ,  20.22610855102539
107 ,  20.223541259765625
108 ,  20.226905822753906
109 ,  20.21918296813965
110 ,  20.222049713134766
111 ,  20.224821090698242
112 ,  20.224912643432617
113 ,  20.24983787536621
114 ,  20.2525634765625
115 ,  20.253299713134766
116 ,  20.254459381103516
117 ,  20.249027252197266
118 ,  20.22222900390625
119 ,  20.18515396118164
120 ,  20.1894588470459
121 ,  20.189598083496094
122 ,  20.19087791442871
123 ,  20.19062042236328
124 ,  20.19356918334961
125 ,  20.193675994873047
126 ,  20.160104751586914
127 ,  20.161033630371094
128 ,  20.164325714111328
129 ,  20.1705322265625
130 ,  20.163150787353516
131 ,  20.171899795532227
132 ,  20.167640686035156
133 ,  20.16419219970703
134 ,  20.165184020996094
135 ,  20.16635513305664
136 ,  20.171892166137695
137 ,  20.17300796508789
138 ,  20.174623489379883
139 ,  20.174171447753906
140 ,  20.040822982788086
141 ,  20.042919158935547
142 ,  20.067302703857422
143 ,  19.957317352294922
144 ,  19.961124420166016
145 ,  19.961551666259766
146 ,  19.96237564086914
147 ,  19.958845138549805
148 ,  19.959556579589844
149 ,  19.959510803222656
150 ,  19.960296630859375
151 ,  19.961544036865234
152 ,  19.96161651611328
153 ,  19.960342407226562
154 ,  19.961273193359375
155 ,  19.966293334960938
156 ,  19.96735382080078
157 ,  19.968414306640625
158 ,  19.96877098083496
159 ,  19.9664306640625
160 ,  19.965755462646484
161 ,  19.96808433532715
162 ,  19.974937438964844
163 ,  19.983139038085938
164 ,  19.981243133544922
165 ,  19.981842041015625
166 ,  19.982494354248047
167 ,  19.961715698242188
168 ,  19.962478637695312
169 ,  19.96344566345215
170 ,  19.96884536743164
171 ,  19.971158981323242
172 ,  19.971546173095703
173 ,  19.96263313293457
174 ,  19.984580993652344
175 ,  19.984771728515625
176 ,  19.983524322509766
177 ,  19.98368263244629
178 ,  19.98462677001953
179 ,  19.991140365600586
180 ,  19.987464904785156
181 ,  19.98785400390625
182 ,  19.98716926574707
183 ,  19.98859405517578
184 ,  19.986427307128906
185 ,  19.972827911376953
186 ,  19.974258422851562
187 ,  19.975086212158203
188 ,  19.96772003173828
189 ,  19.96798324584961
190 ,  19.97698402404785
191 ,  19.981277465820312
192 ,  19.981199264526367
193 ,  19.98240852355957
194 ,  19.96813201904297
195 ,  19.966337203979492
196 ,  19.969738006591797
197 ,  19.971153259277344
198 ,  19.96973419189453
199 ,  19.970050811767578
200 ,  19.969924926757812
201 ,  19.969924926757812
202 ,  19.981590270996094
203 ,  19.98192596435547
204 ,  19.985200881958008
205 ,  19.985637664794922
206 ,  19.97874641418457
207 ,  19.974681854248047
208 ,  19.977474212646484
209 ,  19.966224670410156
210 ,  19.96662139892578
211 ,  19.968585968017578
212 ,  19.956497192382812
213 ,  19.95302963256836
214 ,  19.952877044677734
215 ,  19.9525146484375
216 ,  19.95181655883789
217 ,  19.946693420410156
218 ,  19.956323623657227
219 ,  19.95722007751465
220 ,  19.957080841064453
221 ,  19.9576416015625
222 ,  19.956811904907227
223 ,  19.956979751586914
224 ,  19.959068298339844
225 ,  19.956804275512695
226 ,  19.947711944580078
227 ,  19.9471492767334
228 ,  19.947437286376953
229 ,  19.94182014465332
230 ,  19.928476333618164
231 ,  19.93239402770996
232 ,  19.927412033081055
233 ,  19.94073486328125
234 ,  19.946287155151367
235 ,  19.943687438964844
236 ,  19.941511154174805
237 ,  19.94355010986328
238 ,  19.943511962890625
239 ,  19.94399642944336
240 ,  19.894515991210938
241 ,  19.90256118774414
242 ,  19.942167282104492
243 ,  19.943029403686523
244 ,  19.943212509155273
245 ,  19.943422317504883
246 ,  19.945663452148438
247 ,  19.94357681274414
248 ,  19.943817138671875
249 ,  19.951133728027344
250 ,  19.952198028564453
251 ,  19.952198028564453
252 ,  19.954984664916992
253 ,  19.948820114135742
254 ,  19.949304580688477
255 ,  19.949569702148438
256 ,  19.949832916259766
257 ,  19.950422286987305
258 ,  19.94671630859375
259 ,  19.94704818725586
260 ,  19.94793128967285
261 ,  19.947799682617188
262 ,  19.90707778930664
263 ,  19.907093048095703
264 ,  19.90850067138672
265 ,  19.914628982543945
266 ,  19.914644241333008
267 ,  19.914260864257812
268 ,  19.913511276245117
269 ,  19.914260864257812
270 ,  19.914342880249023
271 ,  19.915388107299805
272 ,  19.905628204345703
273 ,  19.905845642089844
274 ,  19.89719581604004
275 ,  19.897296905517578
276 ,  19.894119262695312
277 ,  19.796337127685547
278 ,  19.79560661315918
279 ,  19.795852661132812
280 ,  19.76028060913086
281 ,  19.759246826171875
282 ,  19.75776481628418
283 ,  19.757831573486328
284 ,  19.757497787475586
285 ,  19.754945755004883
286 ,  19.748214721679688
287 ,  19.752098083496094
288 ,  19.73068618774414
289 ,  19.711780548095703
290 ,  19.712032318115234
291 ,  19.7012882232666
292 ,  19.70142364501953
293 ,  19.69392204284668
294 ,  19.69432830810547
295 ,  19.698944091796875
296 ,  19.696758270263672
297 ,  19.696300506591797
298 ,  19.693321228027344
299 ,  19.618270874023438
300 ,  19.627056121826172
301 ,  19.600341796875
302 ,  19.600915908813477
303 ,  19.60309410095215
304 ,  19.604326248168945
305 ,  19.60422706604004
306 ,  19.607297897338867
307 ,  19.595539093017578
308 ,  19.595048904418945
309 ,  19.595457077026367
310 ,  19.59469985961914
311 ,  19.59649658203125
312 ,  19.596363067626953
313 ,  19.569581985473633
314 ,  19.571443557739258
315 ,  19.571392059326172
316 ,  19.571025848388672
317 ,  19.56879425048828
318 ,  19.572540283203125
319 ,  19.575233459472656
320 ,  19.569847106933594
321 ,  19.569856643676758
322 ,  19.57033348083496
323 ,  19.57008171081543
324 ,  19.57038116455078
325 ,  19.564167022705078
326 ,  19.576824188232422
327 ,  19.48610496520996
328 ,  19.51507568359375
329 ,  19.51438331604004
330 ,  19.51422119140625
331 ,  19.519603729248047
332 ,  19.520042419433594
333 ,  19.512287139892578
334 ,  19.560684204101562
335 ,  19.560226440429688
336 ,  19.538654327392578
337 ,  19.542221069335938
338 ,  19.542545318603516
339 ,  19.541425704956055
340 ,  19.540462493896484
341 ,  19.540390014648438
342 ,  19.540302276611328
343 ,  19.534423828125
344 ,  19.53435707092285
345 ,  19.538999557495117
346 ,  19.53388214111328
347 ,  19.53206443786621
348 ,  19.526020050048828
349 ,  19.525875091552734
350 ,  19.507801055908203
351 ,  19.507877349853516
352 ,  19.505130767822266
353 ,  19.504653930664062
354 ,  19.494930267333984
355 ,  19.494375228881836
356 ,  19.493816375732422
357 ,  19.493385314941406
358 ,  19.493846893310547
359 ,  19.4930477142334
360 ,  19.49749183654785
361 ,  19.498432159423828
362 ,  19.49921417236328
363 ,  19.50112533569336
364 ,  19.500972747802734
365 ,  19.50096893310547
366 ,  19.502655029296875
367 ,  19.522174835205078
368 ,  19.52094078063965
369 ,  19.51455307006836
370 ,  19.515605926513672
371 ,  19.51559829711914
372 ,  19.521835327148438
373 ,  19.52798080444336
374 ,  19.526647567749023
375 ,  19.510602951049805
376 ,  19.509416580200195
377 ,  19.50758934020996
378 ,  19.508073806762695
379 ,  19.505653381347656
380 ,  19.500789642333984
381 ,  19.509429931640625
382 ,  19.493181228637695
383 ,  19.495691299438477
384 ,  19.463651657104492
385 ,  19.43897247314453
386 ,  19.436555862426758
387 ,  19.390844345092773
388 ,  19.38958740234375
389 ,  19.387901306152344
390 ,  19.382179260253906
391 ,  19.381793975830078
392 ,  19.386783599853516
393 ,  19.387069702148438
394 ,  19.387134552001953
395 ,  19.38994789123535
396 ,  19.390165328979492
397 ,  19.386844635009766
398 ,  19.386661529541016
399 ,  19.3855037689209
400 ,  19.377586364746094
401 ,  19.3846435546875
402 ,  19.392925262451172
403 ,  19.38633155822754
404 ,  19.3867130279541
405 ,  19.395832061767578
406 ,  19.395875930786133
407 ,  19.39019775390625
408 ,  19.3959903717041
409 ,  19.393192291259766
410 ,  19.396928787231445
411 ,  19.397016525268555
412 ,  19.397037506103516
413 ,  19.396297454833984
414 ,  19.399871826171875
415 ,  19.356735229492188
416 ,  19.343000411987305
417 ,  19.328744888305664
418 ,  19.3298282623291
419 ,  19.333839416503906
420 ,  19.33017349243164
421 ,  19.32900619506836
422 ,  19.33135223388672
423 ,  19.330215454101562
424 ,  19.328693389892578
425 ,  19.32544708251953
426 ,  19.322925567626953
427 ,  19.325515747070312
428 ,  19.321632385253906
429 ,  19.321523666381836
430 ,  19.320091247558594
431 ,  19.34436798095703
432 ,  19.344215393066406
433 ,  19.34392547607422
434 ,  19.344722747802734
435 ,  19.346023559570312
436 ,  19.344573974609375
437 ,  19.353534698486328
438 ,  19.347789764404297
439 ,  19.342063903808594
440 ,  19.3380126953125
441 ,  19.334909439086914
442 ,  19.32879638671875
443 ,  19.324748992919922
444 ,  19.312149047851562
445 ,  19.318477630615234
446 ,  19.310134887695312
447 ,  19.303451538085938
448 ,  19.300674438476562
449 ,  19.300617218017578
450 ,  19.305110931396484
451 ,  19.2874755859375
452 ,  19.281761169433594
453 ,  19.281787872314453
454 ,  19.293426513671875
455 ,  19.293413162231445
456 ,  19.288225173950195
457 ,  19.317935943603516
458 ,  19.314592361450195
459 ,  19.309497833251953
460 ,  19.14402198791504
461 ,  19.142799377441406
462 ,  19.15081024169922
463 ,  19.149988174438477
464 ,  19.188716888427734
465 ,  19.188417434692383
466 ,  19.168184280395508
467 ,  19.164030075073242
468 ,  19.161792755126953
469 ,  19.156543731689453
470 ,  19.176610946655273
471 ,  19.17216682434082
472 ,  19.171031951904297
473 ,  19.173503875732422
474 ,  19.154905319213867
475 ,  19.161714553833008
476 ,  19.156063079833984
477 ,  19.141393661499023
478 ,  19.15695571899414
479 ,  19.118864059448242
480 ,  19.11280059814453
481 ,  19.078365325927734
482 ,  19.069557189941406
483 ,  19.063827514648438
484 ,  19.03046989440918
485 ,  18.9627628326416
486 ,  18.972763061523438
487 ,  18.969913482666016
488 ,  18.98961067199707
489 ,  19.042783737182617
490 ,  19.043537139892578
491 ,  19.099225997924805
492 ,  19.119443893432617
493 ,  19.14703369140625
494 ,  19.145126342773438
495 ,  19.14605712890625
496 ,  19.141258239746094
497 ,  19.134807586669922
498 ,  19.13699722290039
499 ,  19.130901336669922
500 ,  19.127716064453125
501 ,  19.097763061523438
502 ,  19.100147247314453
503 ,  19.115150451660156
504 ,  19.113788604736328
505 ,  19.123329162597656
506 ,  19.12213134765625
507 ,  19.128236770629883
508 ,  19.130664825439453
509 ,  19.232641220092773
510 ,  19.192729949951172
511 ,  19.18965721130371
512 ,  18.8601131439209
513 ,  18.867431640625
514 ,  18.8288516998291
515 ,  18.403730392456055
516 ,  16.950559616088867
517 ,  16.833744049072266
518 ,  16.687095642089844
519 ,  16.495668411254883
520 ,  16.227628707885742
521 ,  0.06390431523323059
522 ,  0.4270011782646179
523 ,  0.9740098118782043
524 ,  -0.34350788593292236
525 ,  -0.3081618845462799
526 ,  -0.24615958333015442

### Trying other combinations (unconditional)

The first 15 neurons and the last one seem relevant.

In [31]:
hook_list = []
layer, neuron = weakening_df.iloc[-1]["layer"], int(weakening_df.iloc[-1]["subnode_index"])
print(layer, neuron)
hook_list.extend(
        make_hooks(
            unconditional_args,
            layer=layer, neuron=neuron,
            mean_value=0.0,
        )
    )
counter=1
for i, row in weakening_df.iterrows():
    hook_list.extend(
        make_hooks(
            unconditional_args,
            layer=row["layer"], neuron=int(row["subnode_index"]),
            mean_value=0.0,
        )
    )
    counter+=1
    with model.hooks(hook_list):
        logits = model(tokens, attention_mask=attention_mask)
        score = logits[...,-1,model.to_single_token('mic')].item()
    print(counter, score)

19 9428
2 21.19553565979004
3 19.778331756591797
4 18.690719604492188
5 17.854339599609375
6 17.01710319519043
7 15.684441566467285
8 15.494027137756348
9 15.326513290405273
10 15.146973609924316
11 14.218110084533691
12 14.32314682006836
13 10.61269760131836
14 10.616426467895508
15 10.605169296264648
16 7.987966537475586
17 7.986255168914795
18 7.765355587005615
19 7.287669658660889
20 7.287300109863281
21 7.282834053039551
22 7.282846450805664
23 7.289073467254639
24 7.2883429527282715
25 7.289684295654297
26 7.288772106170654
27 7.287337779998779
28 7.28761625289917
29 7.287458419799805
30 7.287285804748535
31 7.2848711013793945
32 7.278609752655029
33 7.272932052612305
34 7.267281532287598
35 7.271599769592285
36 7.283195972442627
37 7.2919816970825195
38 7.291751861572266
39 7.257363319396973
40 7.262372970581055
41 7.262213706970215
42 7.2526068687438965
43 7.255599021911621
44 7.246738433837891
45 7.246380805969238
46 7.253517150878906
47 7.241196632385254
48 7.240120887756348
49 7.226907730102539
50 7.225385665893555
51 7.220229625701904
52 7.219521522521973
53 7.235394477844238
54 7.242377281188965
55 7.240767955780029
56 7.236835479736328
57 7.245563507080078
58 7.248356819152832
59 7.247861862182617
60 7.23109245300293
61 7.230195999145508
62 7.220704078674316
63 7.229846954345703
64 7.207187175750732
65 7.174190044403076
66 7.174917221069336
67 7.175084114074707
68 6.291017532348633
69 6.313484191894531
70 6.415926933288574
71 6.3738298416137695
72 6.373838424682617
73 6.255862236022949
74 6.264767169952393
75 6.1824421882629395
76 6.183197021484375
77 6.214531898498535
78 6.203334808349609
79 6.204364776611328
80 6.204194068908691
81 6.198716640472412
82 6.197782516479492
83 6.19601583480835
84 6.206890106201172
85 6.20687198638916
86 6.185542583465576
87 6.1713056564331055
88 6.245649337768555
89 6.25449275970459
90 6.233341217041016
91 6.2962965965271
92 6.296385765075684
93 6.24560546875
94 6.245601654052734
95 6.255270957946777
96 6.255397319793701
97 6.115497589111328
98 6.115388870239258
99 6.10236930847168
100 6.135595798492432
101 6.162707328796387
102 6.162605285644531
103 6.110691070556641
104 6.1222734451293945
105 6.16037654876709
106 6.167729377746582
107 6.167657852172852
108 6.167538642883301
109 6.158998012542725
110 6.181384563446045
111 6.186047554016113
112 6.176486015319824
113 6.165825366973877
114 6.177179336547852
115 6.177149295806885
116 6.177042007446289
117 6.172639846801758
118 6.177990913391113
119 6.1937127113342285
120 6.180355072021484
121 6.180264472961426
122 6.172366619110107
123 6.195866584777832
124 6.210465431213379
125 6.183507442474365
126 6.198484897613525
127 6.220487117767334
128 6.185031414031982
129 6.185018062591553
130 6.193051338195801
131 6.192956447601318
132 6.193920135498047
133 6.240780353546143
134 6.240326881408691
135 6.240016937255859
136 6.215029716491699
137 6.21501350402832
138 6.195354461669922
139 6.199494361877441
140 6.199011325836182
141 6.2853288650512695
142 6.285159111022949
143 6.3360490798950195
144 6.285469055175781
145 6.2855072021484375
146 6.274472236633301
147 6.270076751708984
148 6.270023345947266
149 6.296095371246338
150 6.2964324951171875
151 6.2429609298706055
152 6.244471073150635
153 6.22706413269043
154 6.226991176605225
155 6.23011589050293
156 6.278791427612305
157 6.27872371673584
158 6.266171455383301
159 6.242490291595459
160 6.242107391357422
161 6.26118278503418
162 6.26127290725708
163 6.2612104415893555
164 6.2622809410095215
165 6.282259941101074
166 6.268365859985352
167 6.27366828918457
168 6.245759010314941
169 6.240144729614258
170 6.227297306060791
171 6.2272772789001465
172 6.21976375579834
173 6.270944595336914
174 6.2792463302612305
175 6.255939960479736
176 6.292048454284668
177 6.2920732498168945
178 6.310155868530273
179 6.305902481079102
180 6.448358535766602
181 6.4549560546875
182 6.457526206970215
183 6.450727939605713
184 6.450728416442871
185 6.450494289398193
186 6.471208572387695
187 6.477039337158203
188 6.478704452514648
189 6.478719711303711
190 6.476165294647217
191 6.479958534240723
192 6.489919662475586
193 6.489897727966309
194 6.5274858474731445
195 6.528907775878906
196 6.524143218994141
197 6.5326151847839355
198 6.527857303619385
199 6.527750492095947
200 6.543972969055176
201 6.4594621658325195
202 6.443410873413086
203 6.43705940246582
204 6.4372758865356445
205 6.437276840209961
206 6.435532569885254
207 6.4355669021606445
208 6.422232627868652
209 6.437737941741943
210 6.440878391265869
211 6.429358005523682
212 6.429736614227295
213 6.429635524749756
214 6.447006702423096
215 6.458108901977539
216 6.4531049728393555
217 6.453096389770508
218 6.452469825744629
219 6.444953918457031
220 6.454570293426514
221 6.4564208984375
222 6.460085391998291
223 6.4599504470825195
224 6.414727210998535
225 6.410676002502441
226 6.41230583190918
227 6.407312393188477
228 6.384982109069824
229 6.3311448097229
230 6.332188129425049
231 6.329090118408203
232 6.347076892852783
233 6.308803558349609
234 6.18077278137207
235 6.179394245147705
236 6.1628923416137695
237 6.147505760192871
238 6.144642353057861
239 6.1236772537231445
240 6.032112121582031
241 6.034089088439941
242 6.035173416137695
243 6.026049613952637
244 5.884922504425049
245 5.885046482086182
246 5.930629730224609
247 5.924355506896973
248 5.880171775817871
249 5.880178928375244
250 5.974776744842529
251 5.899446487426758
252 5.897250175476074
253 5.897066593170166
254 5.831341743469238
255 5.831207752227783
256 5.83220100402832
257 5.839621543884277
258 5.8303728103637695
259 5.830277442932129
260 5.83360481262207
261 5.838954925537109
262 5.838967323303223
263 5.8539581298828125
264 5.855999946594238
265 5.856029987335205
266 5.702582359313965
267 5.700070858001709
268 5.715113639831543
269 5.715147018432617
270 5.613894462585449
271 5.6138916015625
272 5.613859176635742
273 5.6136674880981445
274 5.613613128662109
275 5.620091438293457
276 5.621156692504883
277 5.621143341064453
278 5.632288455963135
279 5.655191421508789
280 5.663068771362305
281 5.663064956665039
282 5.642792701721191
283 5.6428117752075195
284 5.614325046539307
285 5.61433219909668
286 5.659486770629883
287 5.5845441818237305
288 5.525181770324707
289 5.5283379554748535
290 5.5283203125
291 5.528474807739258
292 5.528395652770996
293 5.502106189727783
294 5.445611953735352
295 5.328217506408691
296 5.341238975524902
297 5.320562362670898
298 5.344758987426758
299 5.2609333992004395
300 5.264945983886719
301 5.264375686645508
302 5.242952346801758
303 5.244626998901367
304 5.216847896575928
305 5.2167582511901855
306 5.243247985839844
307 5.243330001831055
308 5.2433881759643555
309 5.258578777313232
310 5.202880859375
311 5.595010757446289
312 5.506118297576904
313 5.507572650909424
314 5.507240295410156
315 5.514449596405029
316 5.5182719230651855
317 5.518399715423584
318 5.519292831420898
319 5.570810317993164
320 5.570788383483887
321 5.591066360473633
322 5.554486274719238
323 5.554483890533447
324 5.495630264282227
325 5.4956817626953125
326 5.529751777648926
327 5.5299272537231445
328 5.479698181152344
329 5.47982120513916
330 5.471395492553711
331 5.480171203613281
332 5.479734420776367
333 5.537030220031738
334 5.528637886047363
335 5.593685626983643
336 5.592851638793945
337 5.610203266143799
338 5.671639442443848
339 5.6716413497924805
340 5.4296417236328125
341 5.429795742034912
342 5.429802894592285
343 5.376712322235107
344 5.393124580383301
345 5.413748264312744
346 5.587423324584961
347 5.562905311584473
348 5.559051036834717
349 5.620457649230957
350 5.6273651123046875
351 5.628244400024414
352 5.627950191497803
353 5.616549491882324
354 5.655254364013672
355 5.586909294128418
356 5.586775779724121
357 5.5230937004089355
358 5.725000381469727
359 5.725058555603027
360 5.734516143798828
361 5.694623947143555
362 5.694575786590576
363 5.694634914398193
364 5.805732250213623
365 5.834878921508789
366 5.807867050170898
367 5.842477798461914
368 5.842463493347168
369 5.858423233032227
370 5.858699798583984
371 5.858701705932617
372 5.858691215515137
373 5.840353012084961
374 5.842345237731934
375 5.841985702514648
376 5.773309230804443
377 5.757307052612305
378 5.7826337814331055
379 5.772216320037842
380 5.772547721862793
381 5.7923808097839355
382 5.792385101318359
383 5.792305946350098
384 5.8117170333862305
385 5.469962120056152
386 5.513900279998779
387 5.497461318969727
388 5.178097724914551
389 5.140337944030762
390 5.140223503112793
391 5.140254497528076
392 5.156253814697266
393 5.156230449676514
394 5.156076908111572
395 5.118852615356445
396 5.069463729858398
397 5.083310127258301
398 5.05760383605957
399 5.088403701782227
400 5.155576705932617
401 5.155577659606934
402 5.1461639404296875
403 5.1461687088012695
404 5.142948627471924
405 5.154504776000977
406 5.154298782348633
407 5.1559319496154785
408 5.160282135009766
409 5.095231056213379
410 5.402503967285156
411 5.377650260925293
412 5.381563186645508
413 5.381596565246582
414 5.381580352783203
415 5.349570274353027
416 5.349498748779297
417 5.349514007568359
418 5.311136722564697
419 5.29178524017334
420 5.2206292152404785
421 5.252668380737305
422 5.258233070373535
423 5.234559535980225
424 5.234607696533203
425 5.2759504318237305
426 5.236335277557373
427 5.3266191482543945
428 5.582949638366699
429 5.589269161224365
430 5.572190284729004
431 5.600949764251709
432 5.558993339538574
433 5.537652015686035
434 5.660884857177734
435 5.659393310546875
436 5.687664031982422
437 5.687686920166016
438 5.687955856323242
439 5.687843322753906
440 5.715876579284668
441 5.705299377441406
442 5.703516006469727
443 5.6578898429870605
444 5.971787452697754
445 5.971831321716309
446 5.971707344055176
447 5.971745491027832
448 5.971600532531738
449 5.973003387451172
450 5.973029613494873
451 5.956331729888916
452 5.953275203704834
453 5.941947937011719
454 5.941956520080566
455 5.920238494873047
456 5.918715953826904
457 5.918607711791992
458 5.91364049911499
459 5.915560245513916
460 5.9158220291137695
461 5.919501304626465
462 5.909371376037598
463 5.908577919006348
464 5.3704328536987305
465 5.352199554443359
466 5.626505374908447
467 5.664559364318848
468 5.630967140197754
469 5.630966663360596
470 5.631126403808594
471 5.63916015625
472 5.636907577514648
473 5.636962890625
474 5.644661903381348
475 5.587568283081055
476 5.484831809997559
477 5.4957475662231445
478 5.409563064575195
479 5.4526801109313965
480 5.475094318389893
481 5.475192070007324
482 5.3853044509887695
483 5.141641616821289
484 5.141904354095459
485 5.141968727111816
486 5.124358177185059
487 4.895791053771973
488 4.879569053649902
489 4.879189491271973
490 4.880294322967529
491 5.061342239379883
492 5.058975696563721
493 4.922005653381348
494 4.937824249267578
495 4.868972301483154
496 4.869181156158447
497 4.771665096282959
498 4.771799087524414
499 4.783064842224121
500 3.4342899322509766
501 3.426513195037842
502 3.6681125164031982
503 3.673611640930176
504 3.6245148181915283
505 3.6271424293518066
506 3.627286672592163
507 1.4651694297790527
508 1.533644676208496
509 1.545935869216919
510 1.799054503440857
511 1.8056066036224365
512 1.788111925125122
513 0.5273117423057556
514 0.5273224115371704
515 0.5382555723190308
516 0.6317391991615295
517 0.6317369937896729
518 0.6619921922683716
519 0.9987171292304993
520 1.020493745803833
521 0.7262722849845886
522 1.129295825958252
523 1.2667183876037598
524 -0.09509915113449097
525 -0.11053197085857391
526 -0.24615958333015442
527 -0.24615958333015442

We get significant drops after ablating 507 or 513 neurons, so neurons number 505 and 511 seem relevant.

In [32]:
hook_list = []
extra_list = [-1, 505,511]
for i in extra_list:
    layer, neuron = weakening_df.iloc[i]["layer"], int(weakening_df.iloc[i]["subnode_index"])
    print(layer, neuron)
    hook_list.extend(
            make_hooks(
                unconditional_args,
                layer=layer, neuron=neuron,
                mean_value=0.0,
            )
        )
counter=len(extra_list)
for i, row in weakening_df.iterrows():
    hook_list.extend(
        make_hooks(
            unconditional_args,
            layer=row["layer"], neuron=int(row["subnode_index"]),
            mean_value=0.0,
        )
    )
    counter+=1
    with model.hooks(hook_list):
        logits = model(tokens, attention_mask=attention_mask)
        score = logits[...,-1,model.to_single_token('mic')].item()
    print(counter, score)

19 9428
18 6799
28 5325
4 20.84912109375
5 19.449995040893555
6 18.406784057617188
7 17.627052307128906
8 16.75486183166504
9 15.319100379943848
10 15.122270584106445
11 14.940174102783203
12 14.754110336303711
13 13.42409896850586
14 13.577224731445312
15 8.380317687988281
16 8.383272171020508
17 8.37763786315918
18 6.944849014282227
19 6.94462776184082
20 6.846426010131836
21 4.99641752243042
22 4.991631031036377
23 4.994928359985352
24 4.994936943054199
25 4.999763488769531
26 4.999791145324707
27 5.041248321533203
28 5.03647518157959
29 5.036261558532715
30 5.03632926940918
31 5.036343097686768
32 5.05977201461792
33 5.03472375869751
34 5.026397705078125
35 4.955720901489258
36 4.97201681137085
37 4.88156795501709
38 4.971934795379639
39 4.998709678649902
40 5.045924186706543
41 4.52802848815918
42 4.536159992218018
43 4.53614616394043
44 4.378337860107422
45 4.447990417480469
46 4.392324447631836
47 4.392243385314941
48 4.515331745147705
49 4.390039920806885
50 4.389725208282471
51 4.349931240081787
52 4.305630207061768
53 4.20014762878418
54 4.224847793579102
55 4.252320289611816
56 4.315354347229004
57 4.308995723724365
58 4.290672302246094
59 4.432762145996094
60 4.464679718017578
61 4.464653491973877
62 4.4852986335754395
63 4.485160827636719
64 4.426872730255127
65 4.581778526306152
66 4.459545135498047
67 4.321908950805664
68 4.306001663208008
69 4.305971145629883
70 1.4268327951431274
71 1.4426608085632324
72 1.5684030055999756
73 1.5262750387191772
74 1.526275634765625
75 1.4149857759475708
76 1.4228293895721436
77 1.3636198043823242
78 1.3638145923614502
79 1.4051603078842163
80 1.3945101499557495
81 1.394777774810791
82 1.3947724103927612
83 1.3934204578399658
84 1.3932682275772095
85 1.3896315097808838
86 1.3990308046340942
87 1.3990325927734375
88 1.3752179145812988
89 1.3536971807479858
90 1.4119222164154053
91 1.418506383895874
92 1.3998444080352783
93 1.4537272453308105
94 1.4537862539291382
95 1.406972885131836
96 1.4069715738296509
97 1.41249680519104
98 1.4125251770019531
99 1.3207427263259888
100 1.3207345008850098
101 1.3134642839431763
102 1.3383731842041016
103 1.3541269302368164
104 1.3541194200515747
105 1.3287303447723389
106 1.3433518409729004
107 1.3524270057678223
108 1.358483076095581
109 1.3584872484207153
110 1.3584964275360107
111 1.346497893333435
112 1.3597500324249268
113 1.3621740341186523
114 1.3535377979278564
115 1.3520954847335815
116 1.3635374307632446
117 1.3635377883911133
118 1.3635209798812866
119 1.3585045337677002
120 1.3597092628479004
121 1.3695557117462158
122 1.3613038063049316
123 1.3612937927246094
124 1.3587555885314941
125 1.370568037033081
126 1.383912205696106
127 1.3708057403564453
128 1.3809938430786133
129 1.3939929008483887
130 1.3727343082427979
131 1.3727335929870605
132 1.3819873332977295
133 1.3819713592529297
134 1.3826329708099365
135 1.4328731298446655
136 1.4323210716247559
137 1.4307844638824463
138 1.4053518772125244
139 1.4053521156311035
140 1.3855006694793701
141 1.3935517072677612
142 1.393519401550293
143 1.4293766021728516
144 1.429383635520935
145 1.610896110534668
146 1.5531386137008667
147 1.5531312227249146
148 1.5421364307403564
149 1.5360774993896484
150 1.5360753536224365
151 1.5626288652420044
152 1.5626263618469238
153 1.5109219551086426
154 1.511343240737915
155 1.4960746765136719
156 1.4960730075836182
157 1.4992280006408691
158 1.5507147312164307
159 1.550708532333374
160 1.5360310077667236
161 1.5146305561065674
162 1.5145955085754395
163 1.529616117477417
164 1.5296220779418945
165 1.5295333862304688
166 1.5300815105438232
167 1.5324256420135498
168 1.522667646408081
169 1.524827241897583
170 1.4990825653076172
171 1.4914259910583496
172 1.4809255599975586
173 1.480923056602478
174 1.4727774858474731
175 1.5149590969085693
176 1.5221290588378906
177 1.4987359046936035
178 1.5438828468322754
179 1.5438904762268066
180 1.5726667642593384
181 1.5621380805969238
182 1.750138521194458
183 1.7582755088806152
184 1.7700910568237305
185 1.7562086582183838
186 1.7562087774276733
187 1.7561488151550293
188 1.7968740463256836
189 1.8034476041793823
190 1.8074705600738525
191 1.80747389793396
192 1.8053131103515625
193 1.8112448453903198
194 1.8171446323394775
195 1.8171427249908447
196 1.866050124168396
197 1.8738682270050049
198 1.8604652881622314
199 1.8836501836776733
200 1.8774542808532715
201 1.8774511814117432
202 1.913245677947998
203 1.7755897045135498
204 1.7404749393463135
205 1.7257887125015259
206 1.7260633707046509
207 1.7260637283325195
208 1.7243571281433105
209 1.724363088607788
210 1.7051819562911987
211 1.7239110469818115
212 1.725783348083496
213 1.7079979181289673
214 1.708013892173767
215 1.7080159187316895
216 1.70497465133667
217 1.7153339385986328
218 1.7087652683258057
219 1.7087645530700684
220 1.7002562284469604
221 1.6777920722961426
222 1.6991660594940186
223 1.7003206014633179
224 1.7038707733154297
225 1.7038719654083252
226 1.6108392477035522
227 1.608490228652954
228 1.5995724201202393
229 1.5990303754806519
230 1.564780831336975
231 1.506608009338379
232 1.5064884424209595
233 1.4996583461761475
234 1.5242547988891602
235 1.4854295253753662
236 1.3635077476501465
237 1.3627939224243164
238 1.341691493988037
239 1.3213685750961304
240 1.3195412158966064
241 1.3050683736801147
242 1.242710828781128
243 1.242885947227478
244 1.2437914609909058
245 1.2376399040222168
246 1.141485333442688
247 1.1414092779159546
248 1.1664533615112305
249 1.164175271987915
250 1.1402218341827393
251 1.1402146816253662
252 1.1937330961227417
253 1.149904727935791
254 1.1509753465652466
255 1.150955319404602
256 1.1233179569244385
257 1.123304843902588
258 1.122495174407959
259 1.126596212387085
260 1.1262211799621582
261 1.1262104511260986
262 1.1271228790283203
263 1.1300632953643799
264 1.1300631761550903
265 1.1388217210769653
266 1.1403789520263672
267 1.1403956413269043
268 1.0889663696289062
269 1.0866590738296509
270 1.0950510501861572
271 1.0950490236282349
272 1.0477261543273926
273 1.0477267503738403
274 1.0477259159088135
275 1.0477185249328613
276 1.0477170944213867
277 1.047668695449829
278 1.0483894348144531
279 1.048386812210083
280 1.053118109703064
281 1.0619865655899048
282 1.0664411783218384
283 1.0664491653442383
284 1.0563364028930664
285 1.056337594985962
286 1.0463966131210327
287 1.0463967323303223
288 1.0721611976623535
289 1.0415854454040527
290 1.0282657146453857
291 1.0292420387268066
292 1.0292396545410156
293 1.029247760772705
294 1.0292450189590454
295 1.0204650163650513
296 0.9994082450866699
297 0.9659915566444397
298 0.9751884341239929
299 0.9677935838699341
300 0.9845503568649292
301 0.9466164112091064
302 0.946107029914856
303 0.946077823638916
304 0.9350354075431824
305 0.9347313046455383
306 0.9236156940460205
307 0.9236093163490295
308 0.9298438429832458
309 0.9298524856567383
310 0.9298542737960815
311 0.9312691688537598
312 0.9225713610649109
313 1.0667260885238647
314 1.0225969552993774
315 1.0232397317886353
316 1.023242473602295
317 1.0271307229995728
318 1.0265235900878906
319 1.0265296697616577
320 1.0264291763305664
321 1.05852472782135
322 1.0585250854492188
323 1.0704548358917236
324 1.0497890710830688
325 1.0497901439666748
326 1.0187492370605469
327 1.0187504291534424
328 1.0300562381744385
329 1.0300672054290771
330 1.011215329170227
331 1.0112195014953613
332 1.0078372955322266
333 1.0136260986328125
334 1.0135741233825684
335 1.0371475219726562
336 1.0325238704681396
337 1.0571166276931763
338 1.05708646774292
339 1.063295602798462
340 1.0820350646972656
341 1.0820372104644775
342 0.9495524168014526
343 0.9495334625244141
344 0.9495317935943604
345 0.9395847320556641
346 0.9456011056900024
347 0.9587894678115845
348 1.0289881229400635
349 1.019692301750183
350 1.0158427953720093
351 1.0389385223388672
352 1.041642189025879
353 1.0416840314865112
354 1.041662573814392
355 1.034099817276001
356 1.05242919921875
357 1.0222084522247314
358 1.0222022533416748
359 0.9957456588745117
360 1.090852975845337
361 1.0908522605895996
362 1.095004677772522
363 1.07157564163208
364 1.0715763568878174
365 1.0715782642364502
366 1.1331861019134521
367 1.151128888130188
368 1.1401287317276
369 1.1736786365509033
370 1.1736958026885986
371 1.1748915910720825
372 1.174911379814148
373 1.1749123334884644
374 1.1749075651168823
375 1.1578528881072998
376 1.1578292846679688
377 1.157678246498108
378 1.1092820167541504
379 1.1009126901626587
380 1.1151037216186523
381 1.1086671352386475
382 1.1087114810943604
383 1.1187158823013306
384 1.1187165975570679
385 1.1187149286270142
386 1.1285736560821533
387 0.9425002932548523
388 0.963974118232727
389 0.9578825831413269
390 0.8405746221542358
391 0.8302234411239624
392 0.8302204012870789
393 0.8302189707756042
394 0.8326414823532104
395 0.8326411247253418
396 0.832636833190918
397 0.8184405565261841
398 0.7971486449241638
399 0.8010227680206299
400 0.794623851776123
401 0.8080253005027771
402 0.8291618824005127
403 0.8291623592376709
404 0.825462281703949
405 0.8254613876342773
406 0.8220350742340088
407 0.8258110880851746
408 0.8258002996444702
409 0.8259630799293518
410 0.8335382342338562
411 0.7925907373428345
412 0.9044710397720337
413 0.8841128945350647
414 0.8818047046661377
415 0.8818042278289795
416 0.8818036317825317
417 0.8725682497024536
418 0.8725672960281372
419 0.8725284934043884
420 0.8588190078735352
421 0.853859543800354
422 0.8378807902336121
423 0.8430349230766296
424 0.8494666218757629
425 0.8391910195350647
426 0.8391917943954468
427 0.8463366627693176
428 0.8404408693313599
429 0.8693616390228271
430 0.9805652499198914
431 0.9832101464271545
432 0.9779559373855591
433 0.9995945692062378
434 0.9851967096328735
435 0.9746415615081787
436 1.0197958946228027
437 1.0201060771942139
438 1.0251836776733398
439 1.0251848697662354
440 1.025207281112671
441 1.0252074003219604
442 1.0447444915771484
443 1.040810465812683
444 1.0390671491622925
445 1.0143258571624756
446 1.257711410522461
447 1.2577133178710938
448 1.257704496383667
449 1.2577030658721924
450 1.2572617530822754
451 1.2573349475860596
452 1.2573355436325073
453 1.2451661825180054
454 1.244207501411438
455 1.2314207553863525
456 1.231416940689087
457 1.212636113166809
458 1.2126230001449585
459 1.2126123905181885
460 1.2101386785507202
461 1.2107422351837158
462 1.2107422351837158
463 1.2114546298980713
464 1.207685947418213
465 1.2076542377471924
466 0.9032278656959534
467 0.897456169128418
468 0.9808781147003174
469 1.0065350532531738
470 0.9943358898162842
471 0.9943230748176575
472 0.994339108467102
473 0.997459888458252
474 0.9968031048774719
475 0.9968060255050659
476 1.003069519996643
477 0.9624459147453308
478 0.9202680587768555
479 0.9209186434745789
480 0.8789114952087402
481 0.9001647233963013
482 0.9043440818786621
483 0.9043042659759521
484 0.861585259437561
485 0.7966400384902954
486 0.7965262532234192
487 0.7965275049209595
488 0.791266918182373
489 0.7321039438247681
490 0.7306889891624451
491 0.7306627035140991
492 0.7312609553337097
493 0.7540503144264221
494 0.7540324926376343
495 0.7324494123458862
496 0.7373189926147461
497 0.7204977869987488
498 0.7205158472061157
499 0.6806257963180542
500 0.6806243658065796
501 0.6906400918960571
502 0.38610219955444336
503 0.3857876658439636
504 0.4280931353569031
505 0.42923176288604736
506 0.4173479676246643
507 0.4174870252609253
508 0.41749292612075806
509 0.41749292612075806
510 0.442413866519928
511 0.44299787282943726
512 0.5302866697311401
513 0.532390832901001
514 0.5273117423057556
515 0.5273117423057556
516 0.5273224115371704
517 0.5382555723190308
518 0.6317391991615295
519 0.6317369937896729
520 0.6619921922683716
521 0.9987171292304993
522 1.020493745803833
523 0.7262722849845886
524 1.129295825958252
525 1.2667183876037598
526 -0.09509915113449097
527 -0.11053197085857391
528 -0.24615958333015442
529 -0.24615958333015442

Sharp drop after 70 neurons, so neuron 70-len(extra_list)-1=66 seems relevant.

In [54]:
def nice_ablation(extra_list):
    hook_list = []
    for i in extra_list:
        layer, neuron = weakening_df.iloc[i]["layer"], int(weakening_df.iloc[i]["subnode_index"])
        print(layer, neuron)
        hook_list.extend(
                make_hooks(
                    unconditional_args,
                    layer=layer, neuron=neuron,
                    mean_value=0.0,
                )
            )
    counter=len(extra_list)
    with model.hooks(hook_list):
        logits = model(tokens, attention_mask=attention_mask)
        score = logits[...,-1,model.to_single_token('mic')].item()
    print(f'ablating only the {counter} extra neurons yields score {score}')
    for i, row in weakening_df.iterrows():
        hook_list.extend(
            make_hooks(
                unconditional_args,
                layer=row["layer"], neuron=int(row["subnode_index"]),
                mean_value=0.0,
            )
        )
        counter+=1
        with model.hooks(hook_list):
            logits = model(tokens, attention_mask=attention_mask)
            score = logits[...,-1,model.to_single_token('mic')].item()
        print(f'ablating {counter} neurons, last of which is {row["layer"], int(row["subnode_index"])}, yields score {score}')
        if counter>len(extra_list)+extra_list[-1]:
            break

In [61]:
extra_list = [-1, 505, 511, 66]
nice_ablation(extra_list)

19 9428
18 6799
28 5325
10 10026
ablating only the 4 extra neurons yields score 20.571409225463867
ablating 5 neurons, last of which is (31, 8581), yields score 20.57946014404297
ablating 6 neurons, last of which is (30, 9996), yields score 19.184572219848633
ablating 7 neurons, last of which is (29, 7261), yields score 18.168004989624023
ablating 8 neurons, last of which is (30, 732), yields score 17.295026779174805
ablating 9 neurons, last of which is (24, 7935), yields score 16.386899948120117
ablating 10 neurons, last of which is (29, 4131), yields score 14.987414360046387
ablating 11 neurons, last of which is (31, 3498), yields score 14.792738914489746
ablating 12 neurons, last of which is (30, 3705), yields score 14.615364074707031
ablating 13 neurons, last of which is (31, 4568), yields score 14.430747985839844
ablating 14 neurons, last of which is (26, 5558), yields score 12.576786041259766
ablating 15 neurons, last of which is (14, 4516), yields score 12.646888732910156
ablating 16 neurons, last of which is (28, 6703), yields score 7.147378921508789
ablating 17 neurons, last of which is (31, 5973), yields score 7.148710250854492
ablating 18 neurons, last of which is (31, 8666), yields score 7.150152683258057
ablating 19 neurons, last of which is (25, 6139), yields score 4.700312614440918
ablating 20 neurons, last of which is (31, 7081), yields score 4.700344562530518
ablating 21 neurons, last of which is (26, 6841), yields score 4.215946674346924
ablating 22 neurons, last of which is (25, 4595), yields score 1.9053763151168823
ablating 23 neurons, last of which is (28, 8918), yields score 1.9041640758514404
ablating 24 neurons, last of which is (31, 10813), yields score 1.9075508117675781
ablating 25 neurons, last of which is (31, 2633), yields score 1.907551646232605
ablating 26 neurons, last of which is (30, 4893), yields score 1.9089272022247314
ablating 27 neurons, last of which is (31, 2743), yields score 1.9089152812957764
ablating 28 neurons, last of which is (4, 4049), yields score 1.9269368648529053
ablating 29 neurons, last of which is (14, 1849), yields score 1.9093196392059326
ablating 30 neurons, last of which is (31, 8839), yields score 1.909287691116333
ablating 31 neurons, last of which is (31, 6064), yields score 1.9093009233474731
ablating 32 neurons, last of which is (31, 6312), yields score 1.9093064069747925
ablating 33 neurons, last of which is (1, 6152), yields score 1.925797462463379
ablating 34 neurons, last of which is (21, 7064), yields score 1.8923709392547607
ablating 35 neurons, last of which is (30, 3306), yields score 1.8880894184112549
ablating 36 neurons, last of which is (18, 5914), yields score 1.8423027992248535
ablating 37 neurons, last of which is (18, 3624), yields score 1.852746605873108
ablating 38 neurons, last of which is (13, 1362), yields score 1.7428098917007446
ablating 39 neurons, last of which is (2, 5267), yields score 1.7827813625335693
ablating 40 neurons, last of which is (13, 1847), yields score 1.7875392436981201
ablating 41 neurons, last of which is (23, 5744), yields score 1.8097989559173584
ablating 42 neurons, last of which is (29, 2983), yields score 1.532741665840149
ablating 43 neurons, last of which is (30, 5045), yields score 1.5355992317199707
ablating 44 neurons, last of which is (31, 6434), yields score 1.535603642463684
ablating 45 neurons, last of which is (27, 3763), yields score 1.4631445407867432
ablating 46 neurons, last of which is (16, 8880), yields score 1.4881255626678467
ablating 47 neurons, last of which is (4, 8423), yields score 1.4702990055084229
ablating 48 neurons, last of which is (31, 1043), yields score 1.4702848196029663
ablating 49 neurons, last of which is (19, 884), yields score 1.5106308460235596
ablating 50 neurons, last of which is (0, 365), yields score 1.4549517631530762
ablating 51 neurons, last of which is (31, 5123), yields score 1.454878568649292
ablating 52 neurons, last of which is (11, 3016), yields score 1.437350869178772
ablating 53 neurons, last of which is (19, 8673), yields score 1.4274406433105469
ablating 54 neurons, last of which is (27, 5070), yields score 1.3801474571228027
ablating 55 neurons, last of which is (17, 2135), yields score 1.3888862133026123
ablating 56 neurons, last of which is (26, 9373), yields score 1.3977199792861938
ablating 57 neurons, last of which is (15, 784), yields score 1.425086259841919
ablating 58 neurons, last of which is (30, 408), yields score 1.4220017194747925
ablating 59 neurons, last of which is (28, 1281), yields score 1.4148569107055664
ablating 60 neurons, last of which is (20, 9541), yields score 1.4860221147537231
ablating 61 neurons, last of which is (9, 2861), yields score 1.4996185302734375
ablating 62 neurons, last of which is (31, 3312), yields score 1.499619483947754
ablating 63 neurons, last of which is (29, 8387), yields score 1.513936161994934
ablating 64 neurons, last of which is (31, 3846), yields score 1.5139222145080566
ablating 65 neurons, last of which is (13, 6094), yields score 1.4926748275756836
ablating 66 neurons, last of which is (26, 7808), yields score 1.5647934675216675
ablating 67 neurons, last of which is (24, 9659), yields score 1.4862353801727295
ablating 68 neurons, last of which is (29, 8563), yields score 1.4336469173431396
ablating 69 neurons, last of which is (26, 5767), yields score 1.4268338680267334
ablating 70 neurons, last of which is (31, 5217), yields score 1.4268327951431274
ablating 71 neurons, last of which is (10, 10026), yields score 1.4268327951431274

Let's also ablate neuron 22-5=17

In [62]:
extra_list.append(17)
nice_ablation(extra_list)

19 9428
18 6799
28 5325
10 10026
25 4595
ablating only the 5 extra neurons yields score 20.64203453063965
ablating 6 neurons, last of which is (31, 8581), yields score 20.64957046508789
ablating 7 neurons, last of which is (30, 9996), yields score 19.18897247314453
ablating 8 neurons, last of which is (29, 7261), yields score 18.296916961669922
ablating 9 neurons, last of which is (30, 732), yields score 17.32617950439453
ablating 10 neurons, last of which is (24, 7935), yields score 16.39739990234375
ablating 11 neurons, last of which is (29, 4131), yields score 14.708066940307617
ablating 12 neurons, last of which is (31, 3498), yields score 14.509256362915039
ablating 13 neurons, last of which is (30, 3705), yields score 14.315394401550293
ablating 14 neurons, last of which is (31, 4568), yields score 14.135855674743652
ablating 15 neurons, last of which is (26, 5558), yields score 8.433174133300781
ablating 16 neurons, last of which is (14, 4516), yields score 7.904938697814941
ablating 17 neurons, last of which is (28, 6703), yields score 3.465778350830078
ablating 18 neurons, last of which is (31, 5973), yields score 3.4658620357513428
ablating 19 neurons, last of which is (31, 8666), yields score 3.48773455619812
ablating 20 neurons, last of which is (25, 6139), yields score 2.289991855621338
ablating 21 neurons, last of which is (31, 7081), yields score 2.2900547981262207
ablating 22 neurons, last of which is (26, 6841), yields score 1.9053763151168823
ablating 23 neurons, last of which is (25, 4595), yields score 1.9053763151168823

Finally (?), let's ablate neurons 17-6=11 and 15-6=9

In [63]:
extra_list.extend([11,9])
nice_ablation(extra_list)

19 9428
18 6799
28 5325
10 10026
25 4595
28 6703
26 5558
ablating only the 7 extra neurons yields score 19.36339569091797
ablating 8 neurons, last of which is (31, 8581), yields score 19.365585327148438
ablating 9 neurons, last of which is (30, 9996), yields score 16.88190460205078
ablating 10 neurons, last of which is (29, 7261), yields score 16.2645320892334
ablating 11 neurons, last of which is (30, 732), yields score 15.44491195678711
ablating 12 neurons, last of which is (24, 7935), yields score 14.512582778930664
ablating 13 neurons, last of which is (29, 4131), yields score 4.585321426391602
ablating 14 neurons, last of which is (31, 3498), yields score 4.575006484985352
ablating 15 neurons, last of which is (30, 3705), yields score 4.512831687927246
ablating 16 neurons, last of which is (31, 4568), yields score 4.495296478271484
ablating 17 neurons, last of which is (26, 5558), yields score 4.495296478271484

In [64]:
extra_list.append(5)
nice_ablation(extra_list)

19 9428
18 6799
28 5325
10 10026
25 4595
28 6703
26 5558
29 4131
ablating only the 8 extra neurons yields score 13.105241775512695
ablating 9 neurons, last of which is (31, 8581), yields score 13.032252311706543
ablating 10 neurons, last of which is (30, 9996), yields score 10.754203796386719
ablating 11 neurons, last of which is (29, 7261), yields score 1.5392382144927979
ablating 12 neurons, last of which is (30, 732), yields score 1.6689170598983765
ablating 13 neurons, last of which is (24, 7935), yields score 4.585321426391602
ablating 14 neurons, last of which is (29, 4131), yields score 4.585321426391602

In [65]:
extra_list.append(2)
nice_ablation(extra_list)

19 9428
18 6799
28 5325
10 10026
25 4595
28 6703
26 5558
29 4131
29 7261
ablating only the 9 extra neurons yields score 0.53655606508255
ablating 10 neurons, last of which is (31, 8581), yields score 0.7168054580688477
ablating 11 neurons, last of which is (30, 9996), yields score 1.5392382144927979
ablating 12 neurons, last of which is (29, 7261), yields score 1.5392382144927979

In [66]:
print(extra_list)

[-1, 505, 511, 66, 17, 11, 9, 5, 2]

### Top-down variable selection from this list

In [69]:
def top_down_selection(extra_list):
    scores = []
    for tested_index in extra_list:
        tested_layer, tested_neuron = weakening_df.iloc[tested_index]["layer"], int(weakening_df.iloc[tested_index]["subnode_index"])
        print("testing", tested_layer, tested_neuron)
        hook_list = []
        for other_index in extra_list:
            if other_index==tested_index:
                continue
            other_layer, other_neuron = weakening_df.iloc[other_index]["layer"], int(weakening_df.iloc[other_index]["subnode_index"])
            hook_list.extend(
                    make_hooks(
                        unconditional_args,
                        layer=other_layer, neuron=other_neuron,
                        mean_value=0.0,
                    )
                )
        with model.hooks(hook_list):
            logits = model(tokens, attention_mask=attention_mask)
            score = logits[...,-1,model.to_single_token('mic')].item()
        scores.append(score)
        print(f'ablating all relevant neurons except the tested one yields score {score}')
    return scores

In [70]:
scores = top_down_selection(extra_list)

testing 19 9428
ablating all relevant neurons except the tested one yields score 2.0624759197235107
testing 18 6799
ablating all relevant neurons except the tested one yields score 1.0580263137817383
testing 28 5325
ablating all relevant neurons except the tested one yields score 1.1810179948806763
testing 10 10026
ablating all relevant neurons except the tested one yields score 1.9695978164672852
testing 25 4595
ablating all relevant neurons except the tested one yields score 3.1584556102752686
testing 28 6703
ablating all relevant neurons except the tested one yields score 6.585380554199219
testing 26 5558
ablating all relevant neurons except the tested one yields score 6.343113422393799
testing 29 4131
ablating all relevant neurons except the tested one yields score 18.503150939941406
testing 29 7261
ablating all relevant neurons except the tested one yields score 13.105241775512695

In [73]:
new_extra_list = extra_list[:1]+extra_list[2:]
print(new_extra_list)

[-1, 511, 66, 17, 11, 9, 5, 2]

In [74]:
scores = top_down_selection(new_extra_list)

testing 19 9428
ablating all relevant neurons except the tested one yields score 3.7353315353393555
testing 28 5325
ablating all relevant neurons except the tested one yields score 2.1548662185668945
testing 10 10026
ablating all relevant neurons except the tested one yields score 3.834749221801758
testing 25 4595
ablating all relevant neurons except the tested one yields score 5.270565032958984
testing 28 6703
ablating all relevant neurons except the tested one yields score 7.596182346343994
testing 26 5558
ablating all relevant neurons except the tested one yields score 7.381309509277344
testing 29 4131
ablating all relevant neurons except the tested one yields score 18.551250457763672
testing 29 7261
ablating all relevant neurons except the tested one yields score 17.818199157714844

## I'm confused about the number of weakening neurons...

In [30]:
from src.weight_analysis_utils.utils import cos

In [33]:
weakening_df = subnodes_df[subnodes_df["subnode_index"].notna()].sort_values("score", ascending=False)

In [49]:
len(weakening_df)

526

In [65]:
from numpy import sign

In [ ]:
for i,row in weakening_df.iterrows():
    layer=row["layer"]
    neuron=int(row["subnode_index"])
    inout = cos(model.blocks[layer].mlp.W_in[:,neuron], model.blocks[layer].mlp.W_out[neuron,:]).item()
    gateout = cos(model.blocks[layer].mlp.W_gate[:,neuron], model.blocks[layer].mlp.W_out[neuron,:]).abs().item()
    gatein = cos(model.blocks[layer].mlp.W_gate[:,neuron], model.blocks[layer].mlp.W_in[:,neuron]).abs().item()
    if inout>=-.5:
        print(layer, neuron, 'inout:', inout)
    if gateout<=.5:
        print(layer, neuron, 'abs gateout:', gateout)
    if gatein*sign(gateout)<=.5:
        print(layer, neuron, 'abs gatein:', gatein)

In [42]:
import gc
from torch.cuda import empty_cache

In [45]:
import os

In [43]:
gc.collect()
empty_cache()

In [46]:
os.environ["PYTORCH_CUDA_ALLOC_CONF"]="expandable_segments:True"

In [47]:
model.process_weights_()

In [67]:
for i,row in weakening_df.iterrows():
    layer=row["layer"]
    neuron=int(row["subnode_index"])
    inout = cos(model.blocks[layer].mlp.W_in[:,neuron], model.blocks[layer].mlp.W_out[neuron,:]).item()
    gateout = cos(model.blocks[layer].mlp.W_gate[:,neuron], model.blocks[layer].mlp.W_out[neuron,:]).item()
    gatein = cos(model.blocks[layer].mlp.W_gate[:,neuron], model.blocks[layer].mlp.W_in[:,neuron]).item()
    if inout>=-.5:
        print(layer, neuron, 'inout:', inout)
    if abs(gateout)<=.5:
        print(layer, neuron, 'abs gateout:', gateout)
    if gatein*sign(gateout)>=-.5:
        print(layer, neuron, 'resigned gatein:', gatein)

In [52]:
from torch import load

In [ ]:
data = load(DATA_DIR + '/results/allenai/OLMo-7B-0424-hf/refactored/data.pt')

In [57]:
data.keys()

dict_keys(['d_model', 'linout', 'gatelin', 'gateout', 'beta', 'randomness', 'norm_gate', 'norm_in', 'norm_out', 'norm_in_out', 'categories', 'category_stats', 'W_gate_start_to_end', 'W_in_start_to_end', 'W_out_start_to_end'])

In [58]:
data['category_stats']

{(1,
  1,
  1): tensor([ 1,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  2,  1, 15, 11,  1, 11,  1,  1,  1]),
 (1,
  1,
  0): tensor([ 0,  2,  6, 10, 14, 38, 18, 16,  9,  1,  4,  1,  2,  2, 13,  0,  1,  4,
          2,  6,  3,  5,  6,  8,  6,  6, 18,  2, 10,  0,  0,  0]),
 (1,
  0,
  1): tensor([1397, 2867, 7379, 6966, 6223, 7206, 7480, 7661, 7076, 6445, 5526, 4821,
         4279, 3926, 3876, 3768, 3420, 3312, 3488, 3692, 3030, 3305, 3075, 3090,
         2342, 2515, 1719, 1066,  404,   50,   39,  228]),
 (1,
  0,
  0): tensor([619,   3,   6,   1,   0,   2,   1,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   1,   1,   0,   0,   0,   2,   4,   7,  10,   1,
           4,   1,   7,   6]),
 (0,
  1,
  1): tensor([  34,  120,  270,  497,  601, 1022, 1156,  921,  839,  893,  710,  697,
          642,  685,  887,  923,  773,  636,  687,  866, 1155, 1162, 1215, 1183,
         1012, 1107,  997,  793,  504,   59,   92,  676]),
 (0,
  1,
  0): tensor([ 8, 10,  3,  5,  2,  1,  3,  2,  2,  0,  0,  0,  0,  0,  0,  0,  2,  2,
          0,  3,  0,  1,  1,  2, 10,  7,  3, 12, 19,  4, 17,  9]),
 (0,
  0,
  1): tensor([ 8941,  7981,  3325,  3439,  4069,  2501,  2117,  2217,  2881,  3458,
          4532,  5145,  5817,  6018,  5733,  5791,  6324,  6536,  6258,  5632,
          6095,  5618,  5838,  5740,  6823,  6434,  7447,  8636,  9748, 10764,
         10730,  9788]),
 (-1,
  1,
  1): tensor([  5,  23,   8,   5,  11,  19,   7,   6,   2,   3,   2,   7,   6,   9,
           8,   3,   4,  11,  11,  12,  11,   9,   7,  17,  15,  19,  29,  14,
          19,  36,  50, 138]),
 (-1,
  1,
  0): tensor([ 0,  1,  5,  5,  9, 17,  3,  7,  6,  3,  2,  2,  1,  3,  7,  2,  2,  1,
          7,  7,  8, 11,  8, 15,  8, 15, 34, 25, 18, 16, 14, 59]),
 (-1,
  0,
  1): tensor([  3,   0,   6,  78,  78, 202, 222, 178, 193, 205, 232, 335, 261, 365,
         484, 521, 482, 506, 554, 789, 706, 897, 858, 949, 786, 882, 739, 457,
         265,  67,  51,  89]),
 (-1,
  0,
  0): tensor([ 0,  0,  0,  1,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  6, 10,  7, 14])}

In [60]:
data['category_stats'][(-1,1,1)]

tensor([  5,  23,   8,   5,  11,  19,   7,   6,   2,   3,   2,   7,   6,   9,
          8,   3,   4,  11,  11,  12,  11,   9,   7,  17,  15,  19,  29,  14,
         19,  36,  50, 138])

In [62]:
for key,value in data['category_stats'].items():
    print(key, value.sum())

(1, 1, 1) tensor(47)
(1, 1, 0) tensor(213)
(1, 0, 1) tensor(121671)
(1, 0, 0) tensor(676)
(0, 1, 1) tensor(23814)
(0, 1, 0) tensor(128)
(0, 0, 1) tensor(192376)
(-1, 1, 1) tensor(526)
(-1, 1, 0) tensor(321)
(-1, 0, 1) tensor(12440)
(-1, 0, 0) tensor(44)

In [68]:
model.cfg.normalization_type

'LNPre'

In [69]:
model.state_dict().keys()

odict_keys(['embed.W_E', 'blocks.0.attn.W_Q', 'blocks.0.attn.W_O', 'blocks.0.attn.b_Q', 'blocks.0.attn.b_O', 'blocks.0.attn.W_K', 'blocks.0.attn.W_V', 'blocks.0.attn.b_K', 'blocks.0.attn.b_V', 'blocks.0.attn.mask', 'blocks.0.attn.IGNORE', 'blocks.0.attn.rotary_sin', 'blocks.0.attn.rotary_cos', 'blocks.0.mlp.W_in', 'blocks.0.mlp.W_out', 'blocks.0.mlp.W_gate', 'blocks.0.mlp.b_in', 'blocks.0.mlp.b_out', 'blocks.1.attn.W_Q', 'blocks.1.attn.W_O', 'blocks.1.attn.b_Q', 'blocks.1.attn.b_O', 'blocks.1.attn.W_K', 'blocks.1.attn.W_V', 'blocks.1.attn.b_K', 'blocks.1.attn.b_V', 'blocks.1.attn.mask', 'blocks.1.attn.IGNORE', 'blocks.1.attn.rotary_sin', 'blocks.1.attn.rotary_cos', 'blocks.1.mlp.W_in', 'blocks.1.mlp.W_out', 'blocks.1.mlp.W_gate', 'blocks.1.mlp.b_in', 'blocks.1.mlp.b_out', 'blocks.2.attn.W_Q', 'blocks.2.attn.W_O', 'blocks.2.attn.b_Q', 'blocks.2.attn.b_O', 'blocks.2.attn.W_K', 'blocks.2.attn.W_V', 'blocks.2.attn.b_K', 'blocks.2.attn.b_V', 'blocks.2.attn.mask', 'blocks.2.attn.IGNORE', 'blocks.2.attn.rotary_sin', 'blocks.2.attn.rotary_cos', 'blocks.2.mlp.W_in', 'blocks.2.mlp.W_out', 'blocks.2.mlp.W_gate', 'blocks.2.mlp.b_in', 'blocks.2.mlp.b_out', 'blocks.3.attn.W_Q', 'blocks.3.attn.W_O', 'blocks.3.attn.b_Q', 'blocks.3.attn.b_O', 'blocks.3.attn.W_K', 'blocks.3.attn.W_V', 'blocks.3.attn.b_K', 'blocks.3.attn.b_V', 'blocks.3.attn.mask', 'blocks.3.attn.IGNORE', 'blocks.3.attn.rotary_sin', 'blocks.3.attn.rotary_cos', 'blocks.3.mlp.W_in', 'blocks.3.mlp.W_out', 'blocks.3.mlp.W_gate', 'blocks.3.mlp.b_in', 'blocks.3.mlp.b_out', 'blocks.4.attn.W_Q', 'blocks.4.attn.W_O', 'blocks.4.attn.b_Q', 'blocks.4.attn.b_O', 'blocks.4.attn.W_K', 'blocks.4.attn.W_V', 'blocks.4.attn.b_K', 'blocks.4.attn.b_V', 'blocks.4.attn.mask', 'blocks.4.attn.IGNORE', 'blocks.4.attn.rotary_sin', 'blocks.4.attn.rotary_cos', 'blocks.4.mlp.W_in', 'blocks.4.mlp.W_out', 'blocks.4.mlp.W_gate', 'blocks.4.mlp.b_in', 'blocks.4.mlp.b_out', 'blocks.5.attn.W_Q', 'blocks.5.attn.W_O', 'blocks.5.attn.b_Q', 'blocks.5.attn.b_O', 'blocks.5.attn.W_K', 'blocks.5.attn.W_V', 'blocks.5.attn.b_K', 'blocks.5.attn.b_V', 'blocks.5.attn.mask', 'blocks.5.attn.IGNORE', 'blocks.5.attn.rotary_sin', 'blocks.5.attn.rotary_cos', 'blocks.5.mlp.W_in', 'blocks.5.mlp.W_out', 'blocks.5.mlp.W_gate', 'blocks.5.mlp.b_in', 'blocks.5.mlp.b_out', 'blocks.6.attn.W_Q', 'blocks.6.attn.W_O', 'blocks.6.attn.b_Q', 'blocks.6.attn.b_O', 'blocks.6.attn.W_K', 'blocks.6.attn.W_V', 'blocks.6.attn.b_K', 'blocks.6.attn.b_V', 'blocks.6.attn.mask', 'blocks.6.attn.IGNORE', 'blocks.6.attn.rotary_sin', 'blocks.6.attn.rotary_cos', 'blocks.6.mlp.W_in', 'blocks.6.mlp.W_out', 'blocks.6.mlp.W_gate', 'blocks.6.mlp.b_in', 'blocks.6.mlp.b_out', 'blocks.7.attn.W_Q', 'blocks.7.attn.W_O', 'blocks.7.attn.b_Q', 'blocks.7.attn.b_O', 'blocks.7.attn.W_K', 'blocks.7.attn.W_V', 'blocks.7.attn.b_K', 'blocks.7.attn.b_V', 'blocks.7.attn.mask', 'blocks.7.attn.IGNORE', 'blocks.7.attn.rotary_sin', 'blocks.7.attn.rotary_cos', 'blocks.7.mlp.W_in', 'blocks.7.mlp.W_out', 'blocks.7.mlp.W_gate', 'blocks.7.mlp.b_in', 'blocks.7.mlp.b_out', 'blocks.8.attn.W_Q', 'blocks.8.attn.W_O', 'blocks.8.attn.b_Q', 'blocks.8.attn.b_O', 'blocks.8.attn.W_K', 'blocks.8.attn.W_V', 'blocks.8.attn.b_K', 'blocks.8.attn.b_V', 'blocks.8.attn.mask', 'blocks.8.attn.IGNORE', 'blocks.8.attn.rotary_sin', 'blocks.8.attn.rotary_cos', 'blocks.8.mlp.W_in', 'blocks.8.mlp.W_out', 'blocks.8.mlp.W_gate', 'blocks.8.mlp.b_in', 'blocks.8.mlp.b_out', 'blocks.9.attn.W_Q', 'blocks.9.attn.W_O', 'blocks.9.attn.b_Q', 'blocks.9.attn.b_O', 'blocks.9.attn.W_K', 'blocks.9.attn.W_V', 'blocks.9.attn.b_K', 'blocks.9.attn.b_V', 'blocks.9.attn.mask', 'blocks.9.attn.IGNORE', 'blocks.9.attn.rotary_sin', 'blocks.9.attn.rotary_cos', 'blocks.9.mlp.W_in', 'blocks.9.mlp.W_out', 'blocks.9.mlp.W_gate', 'blocks.9.mlp.b_in', 'blocks.9.mlp.b_out', 'blocks.10.attn.W_Q', 'blocks.10.attn.W_O', 'blocks.10.attn.b_Q', 'blocks.10.attn.b_O', 'blocks.10.attn.W_K', 'blocks.10.attn.W_V', 'blocks.10.attn.b_K', 'blocks.10.attn.b_V', 'blocks.10.attn.mask', 'blocks.10.attn.IGNORE', 'blocks.10.attn.rotary_sin', 'blocks.10.attn.rotary_cos', 'blocks.10.mlp.W_in', 'blocks.10.mlp.W_out', 'blocks.10.mlp.W_gate', 'blocks.10.mlp.b_in', 'blocks.10.mlp.b_out', 'blocks.11.attn.W_Q', 'blocks.11.attn.W_O', 'blocks.11.attn.b_Q', 'blocks.11.attn.b_O', 'blocks.11.attn.W_K', 'blocks.11.attn.W_V', 'blocks.11.attn.b_K', 'blocks.11.attn.b_V', 'blocks.11.attn.mask', 'blocks.11.attn.IGNORE', 'blocks.11.attn.rotary_sin', 'blocks.11.attn.rotary_cos', 'blocks.11.mlp.W_in', 'blocks.11.mlp.W_out', 'blocks.11.mlp.W_gate', 'blocks.11.mlp.b_in', 'blocks.11.mlp.b_out', 'blocks.12.attn.W_Q', 'blocks.12.attn.W_O', 'blocks.12.attn.b_Q', 'blocks.12.attn.b_O', 'blocks.12.attn.W_K', 'blocks.12.attn.W_V', 'blocks.12.attn.b_K', 'blocks.12.attn.b_V', 'blocks.12.attn.mask', 'blocks.12.attn.IGNORE', 'blocks.12.attn.rotary_sin', 'blocks.12.attn.rotary_cos', 'blocks.12.mlp.W_in', 'blocks.12.mlp.W_out', 'blocks.12.mlp.W_gate', 'blocks.12.mlp.b_in', 'blocks.12.mlp.b_out', 'blocks.13.attn.W_Q', 'blocks.13.attn.W_O', 'blocks.13.attn.b_Q', 'blocks.13.attn.b_O', 'blocks.13.attn.W_K', 'blocks.13.attn.W_V', 'blocks.13.attn.b_K', 'blocks.13.attn.b_V', 'blocks.13.attn.mask', 'blocks.13.attn.IGNORE', 'blocks.13.attn.rotary_sin', 'blocks.13.attn.rotary_cos', 'blocks.13.mlp.W_in', 'blocks.13.mlp.W_out', 'blocks.13.mlp.W_gate', 'blocks.13.mlp.b_in', 'blocks.13.mlp.b_out', 'blocks.14.attn.W_Q', 'blocks.14.attn.W_O', 'blocks.14.attn.b_Q', 'blocks.14.attn.b_O', 'blocks.14.attn.W_K', 'blocks.14.attn.W_V', 'blocks.14.attn.b_K', 'blocks.14.attn.b_V', 'blocks.14.attn.mask', 'blocks.14.attn.IGNORE', 'blocks.14.attn.rotary_sin', 'blocks.14.attn.rotary_cos', 'blocks.14.mlp.W_in', 'blocks.14.mlp.W_out', 'blocks.14.mlp.W_gate', 'blocks.14.mlp.b_in', 'blocks.14.mlp.b_out', 'blocks.15.attn.W_Q', 'blocks.15.attn.W_O', 'blocks.15.attn.b_Q', 'blocks.15.attn.b_O', 'blocks.15.attn.W_K', 'blocks.15.attn.W_V', 'blocks.15.attn.b_K', 'blocks.15.attn.b_V', 'blocks.15.attn.mask', 'blocks.15.attn.IGNORE', 'blocks.15.attn.rotary_sin', 'blocks.15.attn.rotary_cos', 'blocks.15.mlp.W_in', 'blocks.15.mlp.W_out', 'blocks.15.mlp.W_gate', 'blocks.15.mlp.b_in', 'blocks.15.mlp.b_out', 'blocks.16.attn.W_Q', 'blocks.16.attn.W_O', 'blocks.16.attn.b_Q', 'blocks.16.attn.b_O', 'blocks.16.attn.W_K', 'blocks.16.attn.W_V', 'blocks.16.attn.b_K', 'blocks.16.attn.b_V', 'blocks.16.attn.mask', 'blocks.16.attn.IGNORE', 'blocks.16.attn.rotary_sin', 'blocks.16.attn.rotary_cos', 'blocks.16.mlp.W_in', 'blocks.16.mlp.W_out', 'blocks.16.mlp.W_gate', 'blocks.16.mlp.b_in', 'blocks.16.mlp.b_out', 'blocks.17.attn.W_Q', 'blocks.17.attn.W_O', 'blocks.17.attn.b_Q', 'blocks.17.attn.b_O', 'blocks.17.attn.W_K', 'blocks.17.attn.W_V', 'blocks.17.attn.b_K', 'blocks.17.attn.b_V', 'blocks.17.attn.mask', 'blocks.17.attn.IGNORE', 'blocks.17.attn.rotary_sin', 'blocks.17.attn.rotary_cos', 'blocks.17.mlp.W_in', 'blocks.17.mlp.W_out', 'blocks.17.mlp.W_gate', 'blocks.17.mlp.b_in', 'blocks.17.mlp.b_out', 'blocks.18.attn.W_Q', 'blocks.18.attn.W_O', 'blocks.18.attn.b_Q', 'blocks.18.attn.b_O', 'blocks.18.attn.W_K', 'blocks.18.attn.W_V', 'blocks.18.attn.b_K', 'blocks.18.attn.b_V', 'blocks.18.attn.mask', 'blocks.18.attn.IGNORE', 'blocks.18.attn.rotary_sin', 'blocks.18.attn.rotary_cos', 'blocks.18.mlp.W_in', 'blocks.18.mlp.W_out', 'blocks.18.mlp.W_gate', 'blocks.18.mlp.b_in', 'blocks.18.mlp.b_out', 'blocks.19.attn.W_Q', 'blocks.19.attn.W_O', 'blocks.19.attn.b_Q', 'blocks.19.attn.b_O', 'blocks.19.attn.W_K', 'blocks.19.attn.W_V', 'blocks.19.attn.b_K', 'blocks.19.attn.b_V', 'blocks.19.attn.mask', 'blocks.19.attn.IGNORE', 'blocks.19.attn.rotary_sin', 'blocks.19.attn.rotary_cos', 'blocks.19.mlp.W_in', 'blocks.19.mlp.W_out', 'blocks.19.mlp.W_gate', 'blocks.19.mlp.b_in', 'blocks.19.mlp.b_out', 'blocks.20.attn.W_Q', 'blocks.20.attn.W_O', 'blocks.20.attn.b_Q', 'blocks.20.attn.b_O', 'blocks.20.attn.W_K', 'blocks.20.attn.W_V', 'blocks.20.attn.b_K', 'blocks.20.attn.b_V', 'blocks.20.attn.mask', 'blocks.20.attn.IGNORE', 'blocks.20.attn.rotary_sin', 'blocks.20.attn.rotary_cos', 'blocks.20.mlp.W_in', 'blocks.20.mlp.W_out', 'blocks.20.mlp.W_gate', 'blocks.20.mlp.b_in', 'blocks.20.mlp.b_out', 'blocks.21.attn.W_Q', 'blocks.21.attn.W_O', 'blocks.21.attn.b_Q', 'blocks.21.attn.b_O', 'blocks.21.attn.W_K', 'blocks.21.attn.W_V', 'blocks.21.attn.b_K', 'blocks.21.attn.b_V', 'blocks.21.attn.mask', 'blocks.21.attn.IGNORE', 'blocks.21.attn.rotary_sin', 'blocks.21.attn.rotary_cos', 'blocks.21.mlp.W_in', 'blocks.21.mlp.W_out', 'blocks.21.mlp.W_gate', 'blocks.21.mlp.b_in', 'blocks.21.mlp.b_out', 'blocks.22.attn.W_Q', 'blocks.22.attn.W_O', 'blocks.22.attn.b_Q', 'blocks.22.attn.b_O', 'blocks.22.attn.W_K', 'blocks.22.attn.W_V', 'blocks.22.attn.b_K', 'blocks.22.attn.b_V', 'blocks.22.attn.mask', 'blocks.22.attn.IGNORE', 'blocks.22.attn.rotary_sin', 'blocks.22.attn.rotary_cos', 'blocks.22.mlp.W_in', 'blocks.22.mlp.W_out', 'blocks.22.mlp.W_gate', 'blocks.22.mlp.b_in', 'blocks.22.mlp.b_out', 'blocks.23.attn.W_Q', 'blocks.23.attn.W_O', 'blocks.23.attn.b_Q', 'blocks.23.attn.b_O', 'blocks.23.attn.W_K', 'blocks.23.attn.W_V', 'blocks.23.attn.b_K', 'blocks.23.attn.b_V', 'blocks.23.attn.mask', 'blocks.23.attn.IGNORE', 'blocks.23.attn.rotary_sin', 'blocks.23.attn.rotary_cos', 'blocks.23.mlp.W_in', 'blocks.23.mlp.W_out', 'blocks.23.mlp.W_gate', 'blocks.23.mlp.b_in', 'blocks.23.mlp.b_out', 'blocks.24.attn.W_Q', 'blocks.24.attn.W_O', 'blocks.24.attn.b_Q', 'blocks.24.attn.b_O', 'blocks.24.attn.W_K', 'blocks.24.attn.W_V', 'blocks.24.attn.b_K', 'blocks.24.attn.b_V', 'blocks.24.attn.mask', 'blocks.24.attn.IGNORE', 'blocks.24.attn.rotary_sin', 'blocks.24.attn.rotary_cos', 'blocks.24.mlp.W_in', 'blocks.24.mlp.W_out', 'blocks.24.mlp.W_gate', 'blocks.24.mlp.b_in', 'blocks.24.mlp.b_out', 'blocks.25.attn.W_Q', 'blocks.25.attn.W_O', 'blocks.25.attn.b_Q', 'blocks.25.attn.b_O', 'blocks.25.attn.W_K', 'blocks.25.attn.W_V', 'blocks.25.attn.b_K', 'blocks.25.attn.b_V', 'blocks.25.attn.mask', 'blocks.25.attn.IGNORE', 'blocks.25.attn.rotary_sin', 'blocks.25.attn.rotary_cos', 'blocks.25.mlp.W_in', 'blocks.25.mlp.W_out', 'blocks.25.mlp.W_gate', 'blocks.25.mlp.b_in', 'blocks.25.mlp.b_out', 'blocks.26.attn.W_Q', 'blocks.26.attn.W_O', 'blocks.26.attn.b_Q', 'blocks.26.attn.b_O', 'blocks.26.attn.W_K', 'blocks.26.attn.W_V', 'blocks.26.attn.b_K', 'blocks.26.attn.b_V', 'blocks.26.attn.mask', 'blocks.26.attn.IGNORE', 'blocks.26.attn.rotary_sin', 'blocks.26.attn.rotary_cos', 'blocks.26.mlp.W_in', 'blocks.26.mlp.W_out', 'blocks.26.mlp.W_gate', 'blocks.26.mlp.b_in', 'blocks.26.mlp.b_out', 'blocks.27.attn.W_Q', 'blocks.27.attn.W_O', 'blocks.27.attn.b_Q', 'blocks.27.attn.b_O', 'blocks.27.attn.W_K', 'blocks.27.attn.W_V', 'blocks.27.attn.b_K', 'blocks.27.attn.b_V', 'blocks.27.attn.mask', 'blocks.27.attn.IGNORE', 'blocks.27.attn.rotary_sin', 'blocks.27.attn.rotary_cos', 'blocks.27.mlp.W_in', 'blocks.27.mlp.W_out', 'blocks.27.mlp.W_gate', 'blocks.27.mlp.b_in', 'blocks.27.mlp.b_out', 'blocks.28.attn.W_Q', 'blocks.28.attn.W_O', 'blocks.28.attn.b_Q', 'blocks.28.attn.b_O', 'blocks.28.attn.W_K', 'blocks.28.attn.W_V', 'blocks.28.attn.b_K', 'blocks.28.attn.b_V', 'blocks.28.attn.mask', 'blocks.28.attn.IGNORE', 'blocks.28.attn.rotary_sin', 'blocks.28.attn.rotary_cos', 'blocks.28.mlp.W_in', 'blocks.28.mlp.W_out', 'blocks.28.mlp.W_gate', 'blocks.28.mlp.b_in', 'blocks.28.mlp.b_out', 'blocks.29.attn.W_Q', 'blocks.29.attn.W_O', 'blocks.29.attn.b_Q', 'blocks.29.attn.b_O', 'blocks.29.attn.W_K', 'blocks.29.attn.W_V', 'blocks.29.attn.b_K', 'blocks.29.attn.b_V', 'blocks.29.attn.mask', 'blocks.29.attn.IGNORE', 'blocks.29.attn.rotary_sin', 'blocks.29.attn.rotary_cos', 'blocks.29.mlp.W_in', 'blocks.29.mlp.W_out', 'blocks.29.mlp.W_gate', 'blocks.29.mlp.b_in', 'blocks.29.mlp.b_out', 'blocks.30.attn.W_Q', 'blocks.30.attn.W_O', 'blocks.30.attn.b_Q', 'blocks.30.attn.b_O', 'blocks.30.attn.W_K', 'blocks.30.attn.W_V', 'blocks.30.attn.b_K', 'blocks.30.attn.b_V', 'blocks.30.attn.mask', 'blocks.30.attn.IGNORE', 'blocks.30.attn.rotary_sin', 'blocks.30.attn.rotary_cos', 'blocks.30.mlp.W_in', 'blocks.30.mlp.W_out', 'blocks.30.mlp.W_gate', 'blocks.30.mlp.b_in', 'blocks.30.mlp.b_out', 'blocks.31.attn.W_Q', 'blocks.31.attn.W_O', 'blocks.31.attn.b_Q', 'blocks.31.attn.b_O', 'blocks.31.attn.W_K', 'blocks.31.attn.W_V', 'blocks.31.attn.b_K', 'blocks.31.attn.b_V', 'blocks.31.attn.mask', 'blocks.31.attn.IGNORE', 'blocks.31.attn.rotary_sin', 'blocks.31.attn.rotary_cos', 'blocks.31.mlp.W_in', 'blocks.31.mlp.W_out', 'blocks.31.mlp.W_gate', 'blocks.31.mlp.b_in', 'blocks.31.mlp.b_out', 'unembed.W_U', 'unembed.b_U'])

In [70]:
data['category_stats'][(1,1,1)]

tensor([ 1,  1,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  2,  1, 15, 11,  1, 11,  1,  1,  1])